/**
 * bag-upload.test.ts
 *
 * Integration test: POSTs a synthetic BAG (HDF5) buffer to
 * POST /api/datasets/upload and confirms:
 *
 *  1. The multer extension filter accepts ".bag"
 *  2. parseBag runs end-to-end, producing ≥10 valid points
 *  3. The terrain + overview grids are returned in the 200 response
 *  4. The dataset is persisted (db.insert called with userId)
 *  5. An invalid (non-HDF5) buffer yields a 400 parse_error, not a 500
 *
 * The survey.bag fixture is the same one used by real-file-integration.test.ts:
 * a 10×10 Float32 elevation grid with metadata XML, generated by
 * artifacts/api-server/src/__tests__/fixtures/generate.mjs.
 * It has 97 valid cells (3 fill-value cells excluded) — well above the ≥10
 * point minimum required by the upload route.
 *
 * Resolution is pinned to 32 in the happy-path tests: gridPoints IDW fill is
 * O(N⁴) for sparse data, and the default 256 would be slow in CI.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import request from "supertest";

const __dir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

// ── Mocks ─────────────────────────────────────────────────────────────────────
//
// vi.hoisted runs before vi.mock hoisting, so its return value is accessible
// inside the factory closures below.  The mocks track calls so individual
// tests can assert that db.insert received the correct userId.

const dbMockState = vi.hoisted(() => {
  const insertReturningMock = vi.fn().mockResolvedValue([
    {
      id: "bag-test-dataset-id",
      name: "survey bag",
      minDepth: 1000,
      maxDepth: 20000,
      createdAt: new Date("2026-01-01T00:00:00Z"),
    },
  ]);
  const valuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
  const selectWhereMock = vi.fn().mockResolvedValue([]);
  const fromMock = vi.fn().mockReturnValue({ where: selectWhereMock });
  return { insertReturningMock, valuesMock, selectWhereMock, fromMock };
});

vi.mock("@workspace/db", async () => {
  const { createDbMock } = await import("./helpers/db-mock.js");
  return createDbMock({
    db: {
      select: vi.fn().mockReturnValue({ from: dbMockState.fromMock }),
      insert: vi.fn().mockReturnValue({ values: dbMockState.valuesMock }),
    },
  });
});

vi.mock("drizzle-orm", () => ({
  eq: vi.fn(() => "eq-condition"),
  and: vi.fn((...args: unknown[]) => args),
  lt: vi.fn(() => "lt-condition"),
}));

vi.mock("@clerk/express", () => ({
  clerkMiddleware: vi.fn(() => (_req: unknown, _res: unknown, next: () => void) => next()),
  getAuth: vi.fn((req: { headers: Record<string, string> }) => {
    const header = req.headers["x-mock-clerk-user-id"];
    return { userId: header ?? null };
  }),
}));

vi.mock("http-proxy-middleware", () => ({
  createProxyMiddleware: vi.fn(() => (_req: unknown, _res: unknown, next: () => void) => next()),
}));

vi.mock("@clerk/shared/keys", () => ({
  publishableKeyFromHost: vi.fn(() => "pk_test_mock"),
}));

import app from "../app.js";
import { __resetRateLimitMemory } from "../middlewares/rateLimit.js";

beforeEach(() => {
  __resetRateLimitMemory();
});

const AUTHED_HEADER = { "x-mock-clerk-user-id": "user_bag_upload_tests" };

// ── Fixture helper ────────────────────────────────────────────────────────────

function loadBagFixture(): Buffer {
  return readFileSync(join(FIXTURE_DIR, "survey.bag"));
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("POST /api/datasets/upload — .bag upload", () => {
  it(
    "rejects a sparse BAG fixture with 422 + coveragePercent (sparse-survey guard)",
    async () => {
      const bagBuf = loadBagFixture();

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        // The test BAG fixture is sparse at res=32 (<30% grid coverage).
        // The sparse-survey guard (Task #2403) rejects it with 422.
        .field("resolution", "32")
        .attach("file", bagBuf, {
          filename: "survey.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(422);
      expect(res.body).toHaveProperty("error", "sparse_survey");
      expect(res.body).toHaveProperty("coveragePercent");
      expect(typeof res.body.coveragePercent).toBe("number");
      expect(res.body.coveragePercent).toBeLessThan(30);
    },
    20_000,
  );

  it(
    "does not insert into the database when BAG is sparse (422 aborts before db write)",
    async () => {
      const bagBuf = loadBagFixture();

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", bagBuf, {
          filename: "survey.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(422);
      // db.insert().values() must NOT have been called — sparse rejection happens
      // before the dataset is persisted.
      expect(dbMockState.valuesMock).not.toHaveBeenCalled();
    },
    20_000,
  );

  it(
    "returns coveragePercent < 30 in the 422 body for a sparse BAG file",
    async () => {
      const bagBuf = loadBagFixture();

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", bagBuf, {
          filename: "survey.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(422);
      expect(res.body).toHaveProperty("coveragePercent");
      expect(res.body.coveragePercent).toBeLessThan(30);
    },
    20_000,
  );

  it(
    "returns 415 when an unsupported extension is uploaded (extension allowlist enforced)",
    async () => {
      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .attach("file", Buffer.from("irrelevant"), {
          filename: "survey.h5",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(415);
      expect(res.body).toHaveProperty("error", "unsupported_file_type");
    },
    10_000,
  );

  it(
    "returns 422 parse_error when a non-HDF5 buffer is sent with a .bag extension",
    async () => {
      const junk = Buffer.from("this is definitely not an HDF5 / BAG file at all");

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", junk, {
          filename: "corrupt.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(422);
      expect(res.body).toHaveProperty("error", "parse_error");
      expect(res.body).toHaveProperty("details");
      expect(typeof res.body.details).toBe("string");
      expect(res.body.details.length).toBeGreaterThan(0);
    },
    15_000,
  );
});
