/**
 * bag-upload.test.ts
 *
 * Integration test: POSTs a synthetic BAG (HDF5) buffer to
 * POST /api/datasets/upload and confirms:
 *
 *  1. The multer extension filter accepts ".bag"
 *  2. parseBag runs end-to-end, producing ≥10 valid points
 *  3. The terrain + overview grids are returned in the 200 response
 *  4. The dataset is persisted (db.insert called with userId)
 *  5. An invalid (non-HDF5) buffer yields a 400 parse_error, not a 500
 *
 * The survey.bag fixture is the same one used by real-file-integration.test.ts:
 * a 10×10 Float32 elevation grid with metadata XML, generated by
 * artifacts/api-server/src/__tests__/fixtures/generate.mjs.
 * It has 97 valid cells (3 fill-value cells excluded) — well above the ≥10
 * point minimum required by the upload route.
 *
 * Resolution is pinned to 32 in the happy-path tests: gridPoints IDW fill is
 * O(N⁴) for sparse data, and the default 256 would be slow in CI.
 */

import { describe, it, expect, vi } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import request from "supertest";

const __dir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

// ── Mocks ─────────────────────────────────────────────────────────────────────
//
// vi.hoisted runs before vi.mock hoisting, so its return value is accessible
// inside the factory closures below.  The mocks track calls so individual
// tests can assert that db.insert received the correct userId.

const dbMockState = vi.hoisted(() => {
  const insertReturningMock = vi.fn().mockResolvedValue([
    {
      id: "bag-test-dataset-id",
      name: "survey bag",
      minDepth: 1000,
      maxDepth: 20000,
      createdAt: new Date("2026-01-01T00:00:00Z"),
    },
  ]);
  const valuesMock = vi.fn().mockReturnValue({ returning: insertReturningMock });
  const selectWhereMock = vi.fn().mockResolvedValue([]);
  const fromMock = vi.fn().mockReturnValue({ where: selectWhereMock });
  return { insertReturningMock, valuesMock, selectWhereMock, fromMock };
});

vi.mock("@workspace/db", async () => {
  const { createDbMock } = await import("./helpers/db-mock.js");
  return createDbMock({
    db: {
      select: vi.fn().mockReturnValue({ from: dbMockState.fromMock }),
      insert: vi.fn().mockReturnValue({ values: dbMockState.valuesMock }),
    },
  });
});

vi.mock("drizzle-orm", () => ({
  eq: vi.fn(() => "eq-condition"),
  and: vi.fn((...args: unknown[]) => args),
  lt: vi.fn(() => "lt-condition"),
}));

vi.mock("@clerk/express", () => ({
  clerkMiddleware: vi.fn(() => (_req: unknown, _res: unknown, next: () => void) => next()),
  getAuth: vi.fn((req: { headers: Record<string, string> }) => {
    const header = req.headers["x-mock-clerk-user-id"];
    return { userId: header ?? null };
  }),
}));

vi.mock("http-proxy-middleware", () => ({
  createProxyMiddleware: vi.fn(() => (_req: unknown, _res: unknown, next: () => void) => next()),
}));

vi.mock("@clerk/shared/keys", () => ({
  publishableKeyFromHost: vi.fn(() => "pk_test_mock"),
}));

import app from "../app.js";

const AUTHED_HEADER = { "x-mock-clerk-user-id": "user_bag_upload_tests" };

// ── Fixture helper ────────────────────────────────────────────────────────────

function loadBagFixture(): Buffer {
  return readFileSync(join(FIXTURE_DIR, "survey.bag"));
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("POST /api/datasets/upload — .bag upload", () => {
  it(
    "accepts a valid BAG file and returns 200 with terrain and overview grids",
    async () => {
      const bagBuf = loadBagFixture();

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", bagBuf, {
          filename: "survey.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("terrain");
      expect(res.body.terrain).toHaveProperty("depths");
      expect(Array.isArray(res.body.terrain.depths)).toBe(true);
      expect(res.body).toHaveProperty("overview");
      expect(res.body.overview).toHaveProperty("depths");
    },
    20_000,
  );

  it(
    "stores the parsed dataset in the database (db.insert called with correct userId)",
    async () => {
      const bagBuf = loadBagFixture();

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", bagBuf, {
          filename: "survey.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(200);

      // db.insert().values() should have been called with the authenticated userId
      expect(dbMockState.valuesMock).toHaveBeenCalledWith(
        expect.objectContaining({ userId: "user_bag_upload_tests" }),
      );

      // savedDatasetId is echoed from the DB returning() row
      expect(res.body).toHaveProperty("savedDatasetId", "bag-test-dataset-id");
    },
    20_000,
  );

  it(
    "returns 200 with terrain depths that are all positive and finite",
    async () => {
      const bagBuf = loadBagFixture();

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", bagBuf, {
          filename: "survey.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(200);

      const depths: (number | null)[] = res.body.terrain.depths;
      const nonNull = depths.filter((d): d is number => d !== null);
      expect(nonNull.length).toBeGreaterThan(0);
      for (const d of nonNull) {
        expect(Number.isFinite(d)).toBe(true);
        expect(d).toBeGreaterThan(0);
      }
    },
    20_000,
  );

  it(
    "returns 415 when an unsupported extension is uploaded (extension allowlist enforced)",
    async () => {
      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .attach("file", Buffer.from("irrelevant"), {
          filename: "survey.h5",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(415);
      expect(res.body).toHaveProperty("error", "unsupported_file_type");
    },
    10_000,
  );

  it(
    "returns 422 parse_error when a non-HDF5 buffer is sent with a .bag extension",
    async () => {
      const junk = Buffer.from("this is definitely not an HDF5 / BAG file at all");

      const res = await request(app)
        .post("/api/datasets/upload")
        .set(AUTHED_HEADER)
        .field("resolution", "32")
        .attach("file", junk, {
          filename: "corrupt.bag",
          contentType: "application/octet-stream",
        });

      expect(res.status).toBe(422);
      expect(res.body).toHaveProperty("error", "parse_error");
      expect(res.body).toHaveProperty("details");
      expect(typeof res.body.details).toBe("string");
      expect(res.body.details.length).toBeGreaterThan(0);
    },
    15_000,
  );
});
