/**
 * laz-decompress.test.ts
 *
 * Integration tests for the LAZ (compressed LAS) decompression path in
 * parseLasLaz.  The fixture file (survey.laz) is a genuinely LASzip-compressed
 * LAZ 1.2 file produced by gen_laz.py (laspy + lazrs).  laz-perf v0.0.7
 * decompresses it without any mocking, so bugs in the WASM bitstream reader
 * (bad DataView offset, wrong endianness, incorrect getPoint stride, etc.) are
 * caught by the real decoder.
 *
 * The suite validates:
 *   1. Round-trip correctness: real compressed bytes → correct lon/lat/depth
 *   2. Geographic filtering (invalid coords) and depth=0 inclusion (intertidal)
 *   3. Dispatcher routing (.laz vs .las extension)
 *   4. Error paths (bad magic, too-small buffer, WASM init failure)
 *
 * Fixture generated by:
 *   python3 artifacts/api-server/src/__tests__/fixtures/gen_laz.py
 *   (or: node artifacts/api-server/src/__tests__/fixtures/generate.mjs)
 */

import { vi, describe, it, expect, afterAll, afterEach, beforeAll } from "vitest";
import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import * as lazPerfModule from "laz-perf";
import { parseLasLaz, parseUploadedFile } from "../lib/uploadParsers.js";

const __dir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

let lazBuf: Buffer;

// 90 s — WASM laz-perf init can be slow on the shared CI runner.
// Pre-warming here means individual tests never pay the init cost themselves.
beforeAll(async () => {
  lazBuf = await readFile(join(FIXTURE_DIR, "survey.laz"));
  // Pre-warm the WASM decoder so its one-time init cost is borne here,
  // not spread across every it() block.
  await lazPerfModule.createLazPerf();
}, 90_000);

afterAll(() => {
  lazBuf = null!;
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ─── LAZ decompression — happy path ──────────────────────────────────────────

describe("LAZ decompression — real laz-perf round-trip", () => {
  it("decompresses the LAZ fixture and returns valid bathymetry points", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    expect(pts.length).toBeGreaterThanOrEqual(1);
    for (const p of pts) {
      expect(Number.isFinite(p.lon)).toBe(true);
      expect(Number.isFinite(p.lat)).toBe(true);
      expect(Number.isFinite(p.depth)).toBe(true);
      expect(p.lon).toBeGreaterThanOrEqual(-180);
      expect(p.lon).toBeLessThanOrEqual(180);
      expect(p.lat).toBeGreaterThanOrEqual(-90);
      expect(p.lat).toBeLessThanOrEqual(90);
      // depth=0 is a valid intertidal/waterline measurement; allow >= 0
      expect(p.depth).toBeGreaterThanOrEqual(0);
    }
  });

  it("invokes createLazPerf for a .laz file (not for .las)", async () => {
    const spy = vi.spyOn(lazPerfModule, "createLazPerf");
    await parseLasLaz(lazBuf, "my-survey.laz");
    expect(spy).toHaveBeenCalledTimes(1);
  });

  it("does NOT invoke createLazPerf when the extension is .las", async () => {
    const spy = vi.spyOn(lazPerfModule, "createLazPerf");
    await parseLasLaz(lazBuf, "survey.las");
    expect(spy).not.toHaveBeenCalled();
  });

  it("includes the depth=0 point at index 10 (intertidal / waterline measurement)", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    // 15 records total; depth=0 is a valid intertidal measurement, so all 15
    // are returned. The zero-depth-is-valid contract is enforced by
    // parser-zero-depth-projected-crs.test.ts — do NOT filter depth=0 here.
    expect(pts.length).toBe(15);
    const zeroPt = pts.find((p) => p.depth === 0);
    expect(zeroPt).toBeDefined();
  });

  it("derives correct lon/lat from scale and offset in the LAS header", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-133.0);
      expect(p.lon).toBeLessThanOrEqual(-132.0);
      expect(p.lat).toBeGreaterThanOrEqual(55.0);
      expect(p.lat).toBeLessThanOrEqual(56.0);
    }
  });

  it("produces depth values spanning the full fixture range (0–2400 m)", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    const depths = pts.map((p) => p.depth);
    // Fixture has depths 1250–2400 m plus one depth=0 intertidal point
    expect(Math.min(...depths)).toBeCloseTo(0, 0);
    expect(Math.max(...depths)).toBeCloseTo(2400, 0);
    // Non-zero depths should cover the survey range
    const nonZero = depths.filter((d) => d > 0);
    expect(Math.min(...nonZero)).toBeCloseTo(1250, 0);
  });

  it("converts positive-up Z (negative LAS int) to positive-down depth", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    for (const p of pts) {
      // depth=0 is valid for the intertidal point; all others are > 0
      expect(p.depth).toBeGreaterThanOrEqual(0);
    }
  });

  it("routes .laz through parseUploadedFile dispatcher", async () => {
    const pts = await parseUploadedFile(lazBuf, "survey.laz");
    expect(pts.length).toBeGreaterThanOrEqual(1);
    for (const p of pts) {
      // depth=0 is valid for the intertidal point; all others are > 0
      expect(p.depth).toBeGreaterThanOrEqual(0);
    }
  });
});

// ─── LAZ error paths ──────────────────────────────────────────────────────────

describe("LAZ decompression — error paths", () => {
  it("rejects a buffer whose first 4 bytes are not 'LASF'", async () => {
    const bad = Buffer.from("NOT_A_LAS_FILE_AT_ALL");
    await expect(parseLasLaz(bad, "bad.laz")).rejects.toThrow(/LASF/);
  });

  it("rejects a buffer that is too small for the LAS public header", async () => {
    const tiny = Buffer.alloc(100, 0);
    tiny.write("LASF", 0, "ascii");
    await expect(parseLasLaz(tiny, "tiny.laz")).rejects.toThrow(/too small/i);
  });

  it("wraps a laz-perf init failure in a descriptive error message", async () => {
    vi.spyOn(lazPerfModule, "createLazPerf").mockRejectedValueOnce(
      new Error("WASM binary could not be loaded"),
    );

    const err = await parseLasLaz(lazBuf, "survey.laz").catch((e: unknown) => e);
    expect(err).toBeInstanceOf(Error);
    const msg = (err as Error).message;
    expect(msg).toMatch(/LAZ decompression failed/i);
    expect(msg).toMatch(/WASM binary could not be loaded/i);
    expect(msg).toMatch(/las2las|pdal/i);
  });
});
