/**
 * laz-decompress.test.ts
 *
 * Integration tests for the LAZ (compressed LAS) decompression path in
 * parseLasLaz.  Because laz-perf v0.0.7 ships only a LASZip decoder and has no
 * encoder, this suite mocks the laz-perf module so that:
 *
 *   1. The full parseLasLaz code branch is exercised end-to-end:
 *        createLazPerf() → LASZip.open() → getCount() / getPointLength() /
 *        getPoint() → lasPointsToRaw()
 *
 *   2. The mock LASZip.getPoint() writes realistic int32 XYZ values into the
 *      simulated WASM heap at the `dest` offset, exactly as the real laz-perf
 *      WASM would, so DataView reads in parseLasLaz see the right bytes.
 *
 *   3. Tests assert correct geographic filtering (invalid coords skipped),
 *      depth normalisation (positive-down), zero-depth skipping, error paths
 *      (bad magic, laz-perf init failure), and dispatcher routing.
 *
 * The fixture file (survey.laz) has a valid LAS 1.2 public header so
 * parseLasLaz can read scale/offset/format/pointCount without touching the
 * (uncompressed) point data section, which is never reached in the LAZ branch.
 *
 * Fixture generated by:
 *   node artifacts/api-server/src/__tests__/fixtures/generate.mjs
 */

import { vi, describe, it, expect, beforeAll } from "vitest";
import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// ─── laz-perf mock ────────────────────────────────────────────────────────────
//
// vi.mock is hoisted by Vitest's transformer, so it runs before any import.
// The factory sets up a simulated WASM heap and a LASZip stub whose getPoint()
// writes int32 XYZ values at the dest offset — mirroring what the real WASM
// does so that `new DataView(heap.buffer, dest, ptLen)` in parseLasLaz reads
// correct values.
//
// Points match the survey.laz fixture header:
//   scaleXY=1e-6, scaleZ=0.001, offsetX=-133, offsetY=55, offsetZ=0
//   15 records; index 10 has depth=0 (zi=0) and must be skipped by the parser.

vi.mock("laz-perf", () => {
  // ── Simulated WASM heap ─────────────────────────────────────────────────
  // 512 KB — large enough for two _malloc calls (file buffer + point record).
  // All DataView reads in parseLasLaz use (heap.buffer, dest, ptLen) so `dest`
  // must be a valid byte offset within this buffer.
  const HEAP_SIZE = 512 * 1024;
  const heapBuf = new ArrayBuffer(HEAP_SIZE);
  const heapU8 = new Uint8Array(heapBuf);

  // Bump allocator: starts at 4 KB to avoid offset 0 (aids debugging).
  let allocOff = 4096;
  const bump = (n: number) => {
    const p = allocOff;
    allocOff = (allocOff + n + 15) & ~15; // 16-byte aligned
    return p;
  };

  // ── Encoded points ────────────────────────────────────────────────────────
  // Mirror of the raw points written by buildLaz() in generate.mjs.
  // xi / yi / zi are stored as LAS int32 (positive-up Z).
  const SCALE_XY = 0.000001;
  const SCALE_Z  = 0.001;
  const OX = -133.0;
  const OY =  55.0;

  const SOURCE = [
    [-132.500000, 55.200000, 1250],
    [-132.500100, 55.200100, 1300],
    [-132.500200, 55.200200, 1420],
    [-132.500300, 55.200300, 1380],
    [-132.500400, 55.200400, 1500],
    [-132.500500, 55.200500, 1600],
    [-132.500600, 55.200600, 1750],
    [-132.500700, 55.200700, 1800],
    [-132.500800, 55.200800, 1900],
    [-132.500900, 55.200900, 2000],
    [-132.501000, 55.201000,    0],  // depth=0 → zi=0 → skipped by lasPointsToRaw
    [-132.501100, 55.201100, 2100],
    [-132.501200, 55.201200, 2200],
    [-132.501300, 55.201300, 2300],
    [-132.501400, 55.201400, 2400],
  ] as [number, number, number][];

  const ENCODED = SOURCE.map(([lon, lat, dep]) => ({
    xi: Math.round((lon - OX) / SCALE_XY),
    yi: Math.round((lat - OY) / SCALE_XY),
    zi: Math.round(-dep / SCALE_Z),  // positive-up (negative = below sea)
  }));

  const PT_LEN = 20; // format 0 record size

  // ── Mock factory ──────────────────────────────────────────────────────────
  return {
    createLazPerf: vi.fn(async () => {
      // Each createLazPerf() call gets its own point-index so multiple
      // parseLasLaz calls in the same test run don't interfere.
      let ptIdx = 0;

      return {
        _malloc: bump,
        _free: vi.fn(),
        HEAPU8: heapU8,

        LASZip: class MockLASZip {
          open(_ptr: number, _len: number): void {
            ptIdx = 0; // reset index at the start of each file open
          }
          getCount(): number {
            return ENCODED.length;
          }
          getPointLength(): number {
            return PT_LEN;
          }
          getPoint(dest: number): void {
            const pt = ENCODED[ptIdx++]!;
            const v = new DataView(heapBuf, dest, PT_LEN);
            v.setInt32(0, pt.xi, true);
            v.setInt32(4, pt.yi, true);
            v.setInt32(8, pt.zi, true);
          }
          delete(): void { /* no-op */ }
        },
      };
    }),
  };
});

// Dynamic import so uploadParsers receives the mocked laz-perf module.
// (vi.mock is hoisted but the import must still come after it in source order
// for the mock to be active when the module initialises.)
const { parseLasLaz, parseUploadedFile } = await import("../lib/uploadParsers.js");
const { createLazPerf } = await import("laz-perf");

const __dir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

let lazBuf: Buffer;

beforeAll(async () => {
  lazBuf = await readFile(join(FIXTURE_DIR, "survey.laz"));
});

// ─── LAZ decompression — happy path ──────────────────────────────────────────

describe("LAZ decompression — laz-perf mock path", () => {
  it("decompresses the LAZ fixture and returns valid bathymetry points", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    expect(pts.length).toBeGreaterThanOrEqual(1);
    for (const p of pts) {
      expect(Number.isFinite(p.lon)).toBe(true);
      expect(Number.isFinite(p.lat)).toBe(true);
      expect(Number.isFinite(p.depth)).toBe(true);
      expect(p.lon).toBeGreaterThanOrEqual(-180);
      expect(p.lon).toBeLessThanOrEqual(180);
      expect(p.lat).toBeGreaterThanOrEqual(-90);
      expect(p.lat).toBeLessThanOrEqual(90);
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("invokes createLazPerf for a .laz file (not for .las)", async () => {
    vi.mocked(createLazPerf).mockClear();
    await parseLasLaz(lazBuf, "my-survey.laz");
    expect(createLazPerf).toHaveBeenCalledTimes(1);
  });

  it("does NOT invoke createLazPerf when the extension is .las", async () => {
    vi.mocked(createLazPerf).mockClear();
    // Re-use lazBuf — it has a valid LAS header — but pass a .las filename.
    // The uncompressed path reads points directly from the buffer.
    await parseLasLaz(lazBuf, "survey.las");
    expect(createLazPerf).not.toHaveBeenCalled();
  });

  it("filters the depth=0 point that the mock stream includes at index 10", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    // 15 records total, 1 with depth=0 → 14 valid
    expect(pts.length).toBe(14);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("derives correct lon/lat from scale and offset in the LAS header", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-133.0);
      expect(p.lon).toBeLessThanOrEqual(-132.0);
      expect(p.lat).toBeGreaterThanOrEqual(55.0);
      expect(p.lat).toBeLessThanOrEqual(56.0);
    }
  });

  it("produces depth values spanning the fixture survey range (1250–2400 m)", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    const depths = pts.map((p) => p.depth);
    expect(Math.min(...depths)).toBeCloseTo(1250, 0);
    expect(Math.max(...depths)).toBeCloseTo(2400, 0);
  });

  it("converts positive-up Z (negative LAS int) to positive-down depth", async () => {
    const pts = await parseLasLaz(lazBuf, "survey.laz");
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("routes .laz through parseUploadedFile dispatcher", async () => {
    const pts = await parseUploadedFile(lazBuf, "survey.laz");
    expect(pts.length).toBeGreaterThanOrEqual(1);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });
});

// ─── LAZ error paths ──────────────────────────────────────────────────────────

describe("LAZ decompression — error paths", () => {
  it("rejects a buffer whose first 4 bytes are not 'LASF'", async () => {
    const bad = Buffer.from("NOT_A_LAS_FILE_AT_ALL");
    await expect(parseLasLaz(bad, "bad.laz")).rejects.toThrow(/LASF/);
  });

  it("rejects a buffer that is too small for the LAS public header", async () => {
    const tiny = Buffer.alloc(100, 0);
    tiny.write("LASF", 0, "ascii");
    await expect(parseLasLaz(tiny, "tiny.laz")).rejects.toThrow(/too small/i);
  });

  it("wraps a laz-perf init failure in a descriptive error message", async () => {
    vi.mocked(createLazPerf).mockRejectedValueOnce(
      new Error("WASM binary could not be loaded"),
    );

    const err = await parseLasLaz(lazBuf, "survey.laz").catch((e: unknown) => e);
    expect(err).toBeInstanceOf(Error);
    const msg = (err as Error).message;
    expect(msg).toMatch(/LAZ decompression failed/i);
    // Parser must surface the original WASM error so developers can diagnose.
    expect(msg).toMatch(/WASM binary could not be loaded/i);
    // Must provide a concrete fallback path for users.
    expect(msg).toMatch(/las2las|pdal/i);
  });
});
