/**
 * parser-bag-vr.test.ts
 *
 * Tests for the Variable-Resolution BAG (VR BAG) parser path in
 * bag_parser.py / parseBag. Two suites:
 *
 * 1. WGS84 VR BAG (survey_vr.bag)
 *    Generated by generate.mjs using h5wasm; geographic sw_corner values so no
 *    CRS reprojection is needed. Exercises the core parse path: valid depth
 *    extraction, BAG_FILL skipping, coordinate range, and error handling.
 *
 * 2. Projected-CRS VR BAG (generated on-demand by gen_vr_bag.py)
 *    Metadata XML has a geographic bounding box but no EPSG code/WKT, and
 *    sw_corner values are UTM-like (outside ±180 / ±90). Expected: the parser
 *    raises a descriptive CRS error rather than silently returning no points.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { readFile } from "fs/promises";
import { execFileSync } from "child_process";
import { readFileSync, rmSync, existsSync } from "fs";
import { join, dirname } from "path";
import { tmpdir } from "os";
import { fileURLToPath } from "url";
import { parseBag, type RawPoint } from "../lib/uploadParsers.js";

const __dir       = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

// ── helpers ────────────────────────────────────────────────────────────────

function assertValidBathyPoints(pts: RawPoint[], minCount = 1): void {
  expect(pts.length).toBeGreaterThanOrEqual(minCount);
  for (const p of pts) {
    expect(Number.isFinite(p.lon)).toBe(true);
    expect(Number.isFinite(p.lat)).toBe(true);
    expect(Number.isFinite(p.depth)).toBe(true);
    expect(p.lon).toBeGreaterThanOrEqual(-180);
    expect(p.lon).toBeLessThanOrEqual(180);
    expect(p.lat).toBeGreaterThanOrEqual(-90);
    expect(p.lat).toBeLessThanOrEqual(90);
    expect(p.depth).toBeGreaterThan(0);
  }
}

// ── Suite 1: WGS84 VR BAG (survey_vr.bag) ─────────────────────────────────
//
// Fixture geometry (see generate.mjs buildVrBag):
//   2×2 super-grid; each cell has 2×2 refinements at 0.005°/cell
//   bbox: lon [142.0, 142.02], lat [11.0, 11.02]
//   15 valid depth points (1 BAG_FILL injected at flat_idx=1, ref_idx=2)

const BBOX   = { west: 142.0, east: 142.02, south: 11.0, north: 11.02 };
const MARGIN = 0.01;

describe("VR BAG (WGS84) — realistic geographic-CRS fixture", () => {
  let vrBagBuf: Buffer;

  beforeAll(async () => {
    vrBagBuf = await readFile(join(FIXTURE_DIR, "survey_vr.bag"));
  });

  it("parses the VR fixture and returns ≥1 valid depth point", async () => {
    const pts = await parseBag(vrBagBuf);
    assertValidBathyPoints(pts, 1);
  });

  it("all returned points have finite lon/lat within ±180/±90 and positive depth", async () => {
    const pts = await parseBag(vrBagBuf);
    assertValidBathyPoints(pts, 1);
  });

  it("skips cells with depth == BAG_FILL (1 000 000)", async () => {
    const pts = await parseBag(vrBagBuf);
    for (const p of pts) {
      expect(p.depth).not.toBe(1_000_000);
      expect(p.depth).not.toBe(1e6);
    }
  });

  it("coordinates fall within the fixture's declared bounding box", async () => {
    const pts = await parseBag(vrBagBuf);
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(BBOX.west  - MARGIN);
      expect(p.lon).toBeLessThanOrEqual(   BBOX.east  + MARGIN);
      expect(p.lat).toBeGreaterThanOrEqual(BBOX.south - MARGIN);
      expect(p.lat).toBeLessThanOrEqual(   BBOX.north + MARGIN);
    }
  });

  it("throws an error matching /BAG/i for a non-HDF5 buffer", async () => {
    const junk = Buffer.from("not an hdf5 file at all");
    await expect(parseBag(junk)).rejects.toThrow(/BAG/i);
  });
});

// ── Suite 2: Projected-CRS VR BAG (CRS guard path) ────────────────────────
//
// Fixture is generated on-demand by gen_vr_bag.py to a temp path so it does
// not appear in the fixture directory and trip check-fixture-freshness.sh.

describe("VR BAG parser — projected CRS without resolvable metadata", () => {
  const GEN_SCRIPT   = join(FIXTURE_DIR, "gen_vr_bag.py");
  const FIXTURE_PATH = join(tmpdir(), `survey_vr_projected_${Date.now()}.bag`);

  let projectedVrBagBuf: Buffer;

  beforeAll(() => {
    const pythonUserBase =
      process.env.PYTHONUSERBASE ??
      join(__dir, "../../../../.pythonlibs");
    execFileSync("python3", [GEN_SCRIPT, "--out", FIXTURE_PATH], {
      stdio: "pipe",
      env: { ...process.env, PYTHONUSERBASE: pythonUserBase },
    });
    projectedVrBagBuf = readFileSync(FIXTURE_PATH);
  }, 30_000);

  afterAll(() => {
    try { if (existsSync(FIXTURE_PATH)) rmSync(FIXTURE_PATH); } catch { /* ignore */ }
  });

  it(
    "rejects with a CRS error when sw_corner values indicate projected coordinates",
    async () => {
      const err = await parseBag(projectedVrBagBuf).catch((e: unknown) => e);

      expect(err).toBeInstanceOf(Error);
      const msg = (err as Error).message;

      expect(msg).toMatch(/CRS/i);
      expect(msg).not.toMatch(/produced no valid depth points/i);
    },
    30_000,
  );
});
