/**
 * real-file-integration.test.ts
 *
 * Integration tests that load realistic binary fixture files (GeoTIFF, NetCDF,
 * LAS 1.2, LAS 1.4) and run them through the full parser stack, asserting that
 * non-empty terrain grids are produced.
 *
 * Fixtures are generated by:
 *   node artifacts/api-server/src/__tests__/fixtures/generate.mjs
 *
 * Each fixture mimics the characteristics of a real public-domain survey file:
 *   survey.tif      — float32 GeoTIFF, ModelPixelScale=0.01°, GDAL_NODATA=-9999.
 *                     geotiff.writeArrayBuffer forces ModelTiepoint to the
 *                     globe top-left corner [-180, 90, 0] regardless of what you
 *                     pass, so coverage is lon ≈ -180, lat ≈ 90 (20×20 pixels).
 *                     (mirrors USGS/NOAA COG tiles — the parser bug this test
 *                     surfaces is the fileDirectory.getValue() incompatibility
 *                     in geotiff v3)
 *   survey.nc       — NetCDF CDF-1, 2D depth[lat,lon] grid, _FillValue=-32767
 *                     (mirrors GEBCO/HYCOM extracts)
 *   survey_1_2.las  — LAS 1.2 format-0, non-zero XY+Z offsets, one depth=0
 *                     point (mirrors multibeam output)
 *   survey_1_4.las  — LAS 1.4 format-6, 64-bit point count field, 25 points
 *                     (mirrors newer survey tools like Teledyne CARIS/QPS)
 */

import { describe, it, expect, beforeAll } from "vitest";
import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  parseGeoTiff,
  parseNetCdf,
  parseLasLaz,
  parseUploadedFile,
  type RawPoint,
} from "../lib/uploadParsers.js";

const __dir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

// ---------------------------------------------------------------------------
// Fixture buffers — loaded once before all tests
// ---------------------------------------------------------------------------

let tifBuf: Buffer;
let ncBuf: Buffer;
let las12Buf: Buffer;
let las14Buf: Buffer;

beforeAll(async () => {
  [tifBuf, ncBuf, las12Buf, las14Buf] = await Promise.all([
    readFile(join(FIXTURE_DIR, "survey.tif")),
    readFile(join(FIXTURE_DIR, "survey.nc")),
    readFile(join(FIXTURE_DIR, "survey_1_2.las")),
    readFile(join(FIXTURE_DIR, "survey_1_4.las")),
  ]);
});

// ---------------------------------------------------------------------------
// Helper: check that a points array looks like valid bathymetry
// ---------------------------------------------------------------------------

function assertValidBathyPoints(pts: RawPoint[], minCount = 1): void {
  expect(pts.length).toBeGreaterThanOrEqual(minCount);
  for (const p of pts) {
    expect(Number.isFinite(p.lon)).toBe(true);
    expect(Number.isFinite(p.lat)).toBe(true);
    expect(Number.isFinite(p.depth)).toBe(true);
    expect(p.lon).toBeGreaterThanOrEqual(-180);
    expect(p.lon).toBeLessThanOrEqual(180);
    expect(p.lat).toBeGreaterThanOrEqual(-90);
    expect(p.lat).toBeLessThanOrEqual(90);
    expect(p.depth).toBeGreaterThan(0);
  }
}

// ---------------------------------------------------------------------------
// GeoTIFF integration tests
// ---------------------------------------------------------------------------

describe("GeoTIFF — realistic survey fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseGeoTiff(tifBuf);
    assertValidBathyPoints(pts, 10);
  });

  it("skips NODATA pixels (GDAL_NODATA=-9999)", async () => {
    const pts = await parseGeoTiff(tifBuf);
    // Fixture has 20×20 = 400 pixels, 5 NODATA cells → at most 395 valid
    expect(pts.length).toBeLessThanOrEqual(395);
    for (const p of pts) {
      // After abs() the parser applies, no point should equal 9999
      expect(p.depth).not.toBe(9999);
    }
  });

  it("derives correct geographic coordinates from ModelTiepoint+ModelPixelScale", async () => {
    const pts = await parseGeoTiff(tifBuf);
    // geotiff.writeArrayBuffer forces the globe top-left tiepoint [-180, 90, 0].
    // With 20×20 pixels at 0.01°/px: lon ∈ [-180, -179.8], lat ∈ [89.8, 90].
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-180.01);
      expect(p.lon).toBeLessThanOrEqual(-179.79);
      expect(p.lat).toBeGreaterThanOrEqual(89.79);
      expect(p.lat).toBeLessThanOrEqual(90.01);
    }
  });

  it("converts negative elevation values to positive depth", async () => {
    // Fixture stores negative raster values (below sea level); parser should flip
    const pts = await parseGeoTiff(tifBuf);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("routes through parseUploadedFile dispatcher for .tif", async () => {
    const pts = await parseUploadedFile(tifBuf, "survey.tif");
    assertValidBathyPoints(pts, 10);
  });

  it("routes through parseUploadedFile dispatcher for .tiff", async () => {
    const pts = await parseUploadedFile(tifBuf, "bathymetry.tiff");
    assertValidBathyPoints(pts, 10);
  });
});

// ---------------------------------------------------------------------------
// NetCDF integration tests
// ---------------------------------------------------------------------------

describe("NetCDF — realistic GEBCO-style fixture", () => {
  it("parses the fixture and returns non-empty depth points", () => {
    const pts = parseNetCdf(ncBuf);
    assertValidBathyPoints(pts, 10);
  });

  it("skips cells matching _FillValue=-32767", () => {
    const pts = parseNetCdf(ncBuf);
    // Fixture has 10×10=100 cells with 1 fill cell → at most 99 valid points
    expect(pts.length).toBeLessThanOrEqual(99);
    for (const p of pts) {
      expect(p.depth).not.toBe(32767);
    }
  });

  it("covers the expected geographic region (Mariana Trench area)", () => {
    const pts = parseNetCdf(ncBuf);
    // lon: 142.0–142.9, lat: 11.0–11.9
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(141.9);
      expect(p.lon).toBeLessThanOrEqual(143.0);
      expect(p.lat).toBeGreaterThanOrEqual(10.9);
      expect(p.lat).toBeLessThanOrEqual(12.0);
    }
  });

  it("extracts depth values from a 2D grid layout (lat×lon)", () => {
    const pts = parseNetCdf(ncBuf);
    // Depth values in fixture range from 4050 m (min at [0,1]) to ~8950 m
    const depths = pts.map((p) => p.depth);
    expect(Math.min(...depths)).toBeGreaterThan(0);
    expect(Math.max(...depths)).toBeLessThan(20000);
  });

  it("routes through parseUploadedFile dispatcher for .nc", async () => {
    const pts = await parseUploadedFile(ncBuf, "survey.nc");
    assertValidBathyPoints(pts, 10);
  });
});

// ---------------------------------------------------------------------------
// LAS 1.2 integration tests
// ---------------------------------------------------------------------------

describe("LAS 1.2 (format 0) — realistic multibeam fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    assertValidBathyPoints(pts, 10);
  });

  it("applies non-zero XY and Z offsets from the public header", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    // Fixture points are near -132.5°E, 55.2°N
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-133.0);
      expect(p.lon).toBeLessThanOrEqual(-132.0);
      expect(p.lat).toBeGreaterThanOrEqual(55.0);
      expect(p.lat).toBeLessThanOrEqual(56.0);
    }
  });

  it("skips the depth=0 point injected into the fixture", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    // Fixture has 15 points total, 1 with depth=0 → should return 14
    expect(pts.length).toBe(14);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("produces depth values matching the fixture's survey range", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    const depths = pts.map((p) => p.depth);
    expect(Math.min(...depths)).toBeCloseTo(1250, 0);
    expect(Math.max(...depths)).toBeCloseTo(2400, 0);
  });

  it("routes through parseUploadedFile dispatcher for .las", async () => {
    const pts = await parseUploadedFile(las12Buf, "survey_1_2.las");
    assertValidBathyPoints(pts, 10);
  });
});

// ---------------------------------------------------------------------------
// LAS 1.4 integration tests
// ---------------------------------------------------------------------------

describe("LAS 1.4 (format 6) — 64-bit point count fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    assertValidBathyPoints(pts, 10);
  });

  it("reads the 64-bit point count field (offset 247) correctly", async () => {
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    // Fixture has exactly 25 valid points (no zero-depth ones)
    expect(pts.length).toBe(25);
  });

  it("uses non-zero XY offsets and a coarser Z scale (0.001 m)", async () => {
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    // Fixture points: lon near -132.5, lat near 55.2
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-133.0);
      expect(p.lon).toBeLessThanOrEqual(-132.0);
      expect(p.lat).toBeGreaterThanOrEqual(55.0);
      expect(p.lat).toBeLessThanOrEqual(56.0);
    }
  });

  it("correctly handles format-6 record size (30 bytes)", async () => {
    // Point format 6 records are 30 bytes. The parser uses the LAS_POINT_RECORD_SIZE
    // lookup table. If it silently fell back to the wrong size it would produce
    // garbled coordinates — this test catches that.
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    const depths = pts.map((p) => p.depth);
    // Depths increase monotonically: 1000, 1080, 1160, … 2920
    expect(Math.min(...depths)).toBeCloseTo(1000, 0);
    expect(Math.max(...depths)).toBeCloseTo(2920, 0);
  });

  it("routes through parseUploadedFile dispatcher for .las", async () => {
    const pts = await parseUploadedFile(las14Buf, "survey_1_4.las");
    assertValidBathyPoints(pts, 20);
  });
});

// ---------------------------------------------------------------------------
// Cross-format consistency checks
// ---------------------------------------------------------------------------

describe("Cross-format consistency", () => {
  it("all three formats produce finite, positive depth values", async () => {
    const [tifPts, las12Pts, las14Pts] = await Promise.all([
      parseGeoTiff(tifBuf),
      parseLasLaz(las12Buf, "survey_1_2.las"),
      parseLasLaz(las14Buf, "survey_1_4.las"),
    ]);
    const ncPts = parseNetCdf(ncBuf);

    for (const pts of [tifPts, ncPts, las12Pts, las14Pts]) {
      expect(pts.length).toBeGreaterThan(0);
      for (const p of pts) {
        expect(p.depth).toBeGreaterThan(0);
        expect(Number.isFinite(p.depth)).toBe(true);
      }
    }
  });

  it("parseUploadedFile handles all four fixture files without throwing", async () => {
    const results = await Promise.allSettled([
      parseUploadedFile(tifBuf, "survey.tif"),
      Promise.resolve(parseUploadedFile(ncBuf, "survey.nc")),
      parseUploadedFile(las12Buf, "survey_1_2.las"),
      parseUploadedFile(las14Buf, "survey_1_4.las"),
    ]);

    for (const r of results) {
      expect(r.status).toBe("fulfilled");
    }

    const pointCounts = results
      .filter((r): r is PromiseFulfilledResult<RawPoint[]> => r.status === "fulfilled")
      .map((r) => r.value.length);

    for (const count of pointCounts) {
      expect(count).toBeGreaterThanOrEqual(10);
    }
  });
});
