/**
 * real-file-integration.test.ts
 *
 * Integration tests that load realistic binary fixture files (GeoTIFF, NetCDF,
 * LAS 1.2, LAS 1.4, BAG/HDF5) and run them through the full parser stack,
 * asserting that non-empty terrain grids are produced.
 *
 * Fixtures are generated by:
 *   node artifacts/api-server/src/__tests__/fixtures/generate.mjs
 *
 * Each fixture mimics the characteristics of a real public-domain survey file:
 *   survey.tif      — float32 GeoTIFF, ModelPixelScale=0.01°, GDAL_NODATA=-9999.
 *                     geotiff.writeArrayBuffer forces ModelTiepoint to the
 *                     globe top-left corner [-180, 90, 0] regardless of what you
 *                     pass, so coverage is lon ≈ -180, lat ≈ 90 (20×20 pixels).
 *                     (mirrors USGS/NOAA COG tiles — the parser bug this test
 *                     surfaces is the fileDirectory.getValue() incompatibility
 *                     in geotiff v3)
 *   survey.nc       — NetCDF CDF-1, 2D depth[lat,lon] grid, _FillValue=-32767
 *                     (mirrors GEBCO/HYCOM extracts)
 *   survey_1_2.las  — LAS 1.2 format-0, non-zero XY+Z offsets, one depth=0
 *                     point (mirrors multibeam output)
 *   survey_1_4.las  — LAS 1.4 format-6, 64-bit point count field, 25 points
 *                     (mirrors newer survey tools like Teledyne CARIS/QPS)
 *   survey.bag      — BAG/HDF5, 10×10 Float32 elevation grid, 3 fill-value
 *                     cells (1e6), metadata XML bounding box
 *                     (mirrors NOAA hydrographic survey archives)
 */

import { describe, it, expect, beforeAll } from "vitest";
import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  parseGeoTiff,
  parseNetCdf,
  parseLasLaz,
  parseBag,
  parseGpxTerrain,
  parseNmea,
  parseUploadedFile,
  type RawPoint,
} from "../lib/uploadParsers.js";

const __dir = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(__dir, "fixtures");

// ---------------------------------------------------------------------------
// Fixture buffers — loaded once before all tests
// ---------------------------------------------------------------------------

let tifBuf: Buffer;
let ncBuf: Buffer;
let las12Buf: Buffer;
let las14Buf: Buffer;
let bagBuf: Buffer;
let gpxBuf: Buffer;
let nmeaBuf: Buffer;

beforeAll(async () => {
  [tifBuf, ncBuf, las12Buf, las14Buf, bagBuf, gpxBuf, nmeaBuf] = await Promise.all([
    readFile(join(FIXTURE_DIR, "survey.tif")),
    readFile(join(FIXTURE_DIR, "survey.nc")),
    readFile(join(FIXTURE_DIR, "survey_1_2.las")),
    readFile(join(FIXTURE_DIR, "survey_1_4.las")),
    readFile(join(FIXTURE_DIR, "survey.bag")),
    readFile(join(FIXTURE_DIR, "survey.gpx")),
    readFile(join(FIXTURE_DIR, "survey.nmea")),
  ]);
});

// ---------------------------------------------------------------------------
// Helper: check that a points array looks like valid bathymetry
// ---------------------------------------------------------------------------

function assertValidBathyPoints(pts: RawPoint[], minCount = 1): void {
  expect(pts.length).toBeGreaterThanOrEqual(minCount);
  for (const p of pts) {
    expect(Number.isFinite(p.lon)).toBe(true);
    expect(Number.isFinite(p.lat)).toBe(true);
    expect(Number.isFinite(p.depth)).toBe(true);
    expect(p.lon).toBeGreaterThanOrEqual(-180);
    expect(p.lon).toBeLessThanOrEqual(180);
    expect(p.lat).toBeGreaterThanOrEqual(-90);
    expect(p.lat).toBeLessThanOrEqual(90);
    expect(p.depth).toBeGreaterThan(0);
  }
}

// ---------------------------------------------------------------------------
// GeoTIFF integration tests
// ---------------------------------------------------------------------------

describe("GeoTIFF — realistic survey fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseGeoTiff(tifBuf);
    assertValidBathyPoints(pts, 10);
  });

  it("skips NODATA pixels (GDAL_NODATA=-9999)", async () => {
    const pts = await parseGeoTiff(tifBuf);
    // Fixture has 20×20 = 400 pixels, 5 NODATA cells → at most 395 valid
    expect(pts.length).toBeLessThanOrEqual(395);
    for (const p of pts) {
      // After abs() the parser applies, no point should equal 9999
      expect(p.depth).not.toBe(9999);
    }
  });

  it("derives correct geographic coordinates from ModelTiepoint+ModelPixelScale", async () => {
    const pts = await parseGeoTiff(tifBuf);
    // geotiff.writeArrayBuffer forces the globe top-left tiepoint [-180, 90, 0].
    // With 20×20 pixels at 0.01°/px: lon ∈ [-180, -179.8], lat ∈ [89.8, 90].
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-180.01);
      expect(p.lon).toBeLessThanOrEqual(-179.79);
      expect(p.lat).toBeGreaterThanOrEqual(89.79);
      expect(p.lat).toBeLessThanOrEqual(90.01);
    }
  });

  it("converts negative elevation values to positive depth", async () => {
    // Fixture stores negative raster values (below sea level); parser should flip
    const pts = await parseGeoTiff(tifBuf);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("routes through parseUploadedFile dispatcher for .tif", async () => {
    const pts = await parseUploadedFile(tifBuf, "survey.tif");
    assertValidBathyPoints(pts, 10);
  });

  it("routes through parseUploadedFile dispatcher for .tiff", async () => {
    const pts = await parseUploadedFile(tifBuf, "bathymetry.tiff");
    assertValidBathyPoints(pts, 10);
  });
});

// ---------------------------------------------------------------------------
// NetCDF integration tests
// ---------------------------------------------------------------------------

describe("NetCDF — realistic GEBCO-style fixture", () => {
  it("parses the fixture and returns non-empty depth points", () => {
    const pts = parseNetCdf(ncBuf);
    assertValidBathyPoints(pts, 10);
  });

  it("skips cells matching _FillValue=-32767", () => {
    const pts = parseNetCdf(ncBuf);
    // Fixture has 10×10=100 cells with 1 fill cell → at most 99 valid points
    expect(pts.length).toBeLessThanOrEqual(99);
    for (const p of pts) {
      expect(p.depth).not.toBe(32767);
    }
  });

  it("covers the expected geographic region (Mariana Trench area)", () => {
    const pts = parseNetCdf(ncBuf);
    // lon: 142.0–142.9, lat: 11.0–11.9
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(141.9);
      expect(p.lon).toBeLessThanOrEqual(143.0);
      expect(p.lat).toBeGreaterThanOrEqual(10.9);
      expect(p.lat).toBeLessThanOrEqual(12.0);
    }
  });

  it("extracts depth values from a 2D grid layout (lat×lon)", () => {
    const pts = parseNetCdf(ncBuf);
    // Depth values in fixture range from 4050 m (min at [0,1]) to ~8950 m
    const depths = pts.map((p) => p.depth);
    expect(Math.min(...depths)).toBeGreaterThan(0);
    expect(Math.max(...depths)).toBeLessThan(20000);
  });

  it("routes through parseUploadedFile dispatcher for .nc", async () => {
    const pts = await parseUploadedFile(ncBuf, "survey.nc");
    assertValidBathyPoints(pts, 10);
  });
});

// ---------------------------------------------------------------------------
// LAS 1.2 integration tests
// ---------------------------------------------------------------------------

describe("LAS 1.2 (format 0) — realistic multibeam fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    assertValidBathyPoints(pts, 10);
  });

  it("applies non-zero XY and Z offsets from the public header", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    // Fixture points are near -132.5°E, 55.2°N
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-133.0);
      expect(p.lon).toBeLessThanOrEqual(-132.0);
      expect(p.lat).toBeGreaterThanOrEqual(55.0);
      expect(p.lat).toBeLessThanOrEqual(56.0);
    }
  });

  it("skips the depth=0 point injected into the fixture", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    // Fixture has 15 points total, 1 with depth=0 → should return 14
    expect(pts.length).toBe(14);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("produces depth values matching the fixture's survey range", async () => {
    const pts = await parseLasLaz(las12Buf, "survey_1_2.las");
    const depths = pts.map((p) => p.depth);
    expect(Math.min(...depths)).toBeCloseTo(1250, 0);
    expect(Math.max(...depths)).toBeCloseTo(2400, 0);
  });

  it("routes through parseUploadedFile dispatcher for .las", async () => {
    const pts = await parseUploadedFile(las12Buf, "survey_1_2.las");
    assertValidBathyPoints(pts, 10);
  });
});

// ---------------------------------------------------------------------------
// LAS 1.4 integration tests
// ---------------------------------------------------------------------------

describe("LAS 1.4 (format 6) — 64-bit point count fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    assertValidBathyPoints(pts, 10);
  });

  it("reads the 64-bit point count field (offset 247) correctly", async () => {
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    // Fixture has exactly 25 valid points (no zero-depth ones)
    expect(pts.length).toBe(25);
  });

  it("uses non-zero XY offsets and a coarser Z scale (0.001 m)", async () => {
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    // Fixture points: lon near -132.5, lat near 55.2
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-133.0);
      expect(p.lon).toBeLessThanOrEqual(-132.0);
      expect(p.lat).toBeGreaterThanOrEqual(55.0);
      expect(p.lat).toBeLessThanOrEqual(56.0);
    }
  });

  it("correctly handles format-6 record size (30 bytes)", async () => {
    // Point format 6 records are 30 bytes. The parser uses the LAS_POINT_RECORD_SIZE
    // lookup table. If it silently fell back to the wrong size it would produce
    // garbled coordinates — this test catches that.
    const pts = await parseLasLaz(las14Buf, "survey_1_4.las");
    const depths = pts.map((p) => p.depth);
    // Depths increase monotonically: 1000, 1080, 1160, … 2920
    expect(Math.min(...depths)).toBeCloseTo(1000, 0);
    expect(Math.max(...depths)).toBeCloseTo(2920, 0);
  });

  it("routes through parseUploadedFile dispatcher for .las", async () => {
    const pts = await parseUploadedFile(las14Buf, "survey_1_4.las");
    assertValidBathyPoints(pts, 20);
  });
});

// ---------------------------------------------------------------------------
// BAG (HDF5) integration tests
// ---------------------------------------------------------------------------

describe("BAG (HDF5) — realistic NOAA hydrographic survey fixture", () => {
  it("parses the fixture and returns non-empty depth points", async () => {
    const pts = await parseBag(bagBuf);
    // 10×10 = 100 cells, 3 fill cells → at least 97 valid points
    assertValidBathyPoints(pts, 90);
  });

  it("skips BAG fill-value cells (1e6 / 1_000_000)", async () => {
    const pts = await parseBag(bagBuf);
    // Fixture has 3 cells with fill value 1_000_000
    expect(pts.length).toBeLessThanOrEqual(97);
    for (const p of pts) {
      expect(p.depth).not.toBe(1_000_000);
      expect(p.depth).not.toBe(1e6);
    }
  });

  it("derives geolocation from metadata XML bounding box", async () => {
    const pts = await parseBag(bagBuf);
    // Fixture metadata XML: west=142.0, east=142.01, south=11.0, north=11.01
    // extractBagGeolocation computes cols=round(0.01/0.001)=10, rows=10,
    // so valid points fall within the bounding box.
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(141.99);
      expect(p.lon).toBeLessThanOrEqual(142.02);
      expect(p.lat).toBeGreaterThanOrEqual(10.99);
      expect(p.lat).toBeLessThanOrEqual(11.02);
    }
  });

  it("converts negative elevation values to positive depth", async () => {
    // Fixture stores negative values (positive-up seafloor convention);
    // parseBag must flip them to positive-downward depth.
    const pts = await parseBag(bagBuf);
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("produces depth values within the fixture's survey range", async () => {
    // Fixture depths: -(1000 + idx * 200), idx 1..98 (excluding 3 fill cells).
    // Range: 1200 m (idx=1) to ~20600 m (idx=98), fill-skipped cells excluded.
    const pts = await parseBag(bagBuf);
    const depths = pts.map((p) => p.depth);
    expect(Math.min(...depths)).toBeGreaterThanOrEqual(1000);
    expect(Math.max(...depths)).toBeLessThanOrEqual(25000);
  });

  it("routes through parseUploadedFile dispatcher for .bag", async () => {
    const pts = await parseUploadedFile(bagBuf, "survey.bag");
    assertValidBathyPoints(pts, 90);
  });

  it("throws a descriptive error for a non-HDF5 buffer", async () => {
    // h5wasm silently accepts invalid data without throwing; parseBag must
    // still surface a human-readable error when the file yields no valid points.
    const junk = Buffer.from("not an hdf5 file at all");
    await expect(parseBag(junk)).rejects.toThrow(/BAG file/i);
  });
});

// ---------------------------------------------------------------------------
// GPX integration tests
// ---------------------------------------------------------------------------

describe("GPX — realistic survey track fixture", () => {
  it("parses the fixture and returns 12 valid depth points", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // 10 trkpts + 2 wpts with valid <ele>; 1 trkpt missing <ele>, 1 out-of-range lat,
    // and 1 wpt missing <ele> are all skipped.
    expect(pts.length).toBe(12);
    assertValidBathyPoints(pts, 12);
  });

  it("skips <trkpt> elements that have no <ele> child", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // Fixture injects one trkpt at lat=55.21, lon=-132.51 without <ele>.
    // If it were parsed its lon would be -132.51 — assert no such point exists.
    const noElePt = pts.find(
      (p) => Math.abs(p.lat - 55.21) < 0.00001 && Math.abs(p.lon - -132.51) < 0.00001,
    );
    expect(noElePt).toBeUndefined();
  });

  it("skips <trkpt> with coordinates outside the valid geographic range", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // Fixture injects trkpt with lat=95 (invalid) — no point should have lat > 90.
    for (const p of pts) {
      expect(p.lat).toBeLessThanOrEqual(90);
      expect(p.lat).toBeGreaterThanOrEqual(-90);
    }
  });

  it("processes <wpt> waypoint elements in addition to <trkpt> track points", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // The two valid wpts are at lat≈55.22 and lat≈55.221 — assert both present.
    const wptPts = pts.filter((p) => p.lat >= 55.219 && p.lat <= 55.222);
    expect(wptPts.length).toBe(2);
  });

  it("converts negative <ele> values to positive depth", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // All trkpts have ele < 0; parser must flip sign.
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(0);
    }
  });

  it("also handles positive <ele> values (WP02 has ele=1800.5)", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // WP02 at lat≈55.221 has ele=1800.5 (positive); depth should be 1800.5.
    const wp2 = pts.find((p) => Math.abs(p.lat - 55.221) < 0.00001);
    expect(wp2).toBeDefined();
    expect(wp2!.depth).toBeCloseTo(1800.5, 1);
  });

  it("derives geographic coordinates directly from lat/lon attributes", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    // All fixture trkpts are near lon=-132.5, lat=55.2; wpts near lon=-132.52.
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-132.53);
      expect(p.lon).toBeLessThanOrEqual(-132.49);
      expect(p.lat).toBeGreaterThanOrEqual(55.19);
      expect(p.lat).toBeLessThanOrEqual(55.23);
    }
  });

  it("produces depth values spanning the fixture's survey range", () => {
    const pts = parseGpxTerrain(gpxBuf.toString("utf8"));
    const depths = pts.map((p) => p.depth);
    // trkpt depths: 1250–2150 m; wpt depths: 1800.5, 2000
    expect(Math.min(...depths)).toBeCloseTo(1250, 0);
    expect(Math.max(...depths)).toBeCloseTo(2150, 0);
  });

  it("routes through parseUploadedFile dispatcher for .gpx", async () => {
    const pts = await parseUploadedFile(gpxBuf, "survey.gpx");
    assertValidBathyPoints(pts, 10);
    expect(pts.length).toBe(12);
  });
});

// ---------------------------------------------------------------------------
// NMEA integration tests
// ---------------------------------------------------------------------------

describe("NMEA — realistic depth-sounder log fixture", () => {
  it("parses the fixture and returns 11 valid depth+position pairs", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    // 8 GPGGA+SDDBT + 2 GPRMC+SDDBT + 1 SDDBT (after malformed GPGGA, last valid pos reused)
    // 1 leading SDDBT (no position yet) is skipped.
    expect(pts.length).toBe(11);
    assertValidBathyPoints(pts, 11);
  });

  it("skips the SDDBT sentence that precedes any position fix", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    // The very first sentence is an SDDBT at depth=5.0m — if it were included,
    // a point near depth=5 would appear; no valid point should have depth≤5.
    for (const p of pts) {
      expect(p.depth).toBeGreaterThan(5);
    }
  });

  it("skips sentences whose NMEA checksum is invalid", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    // The malformed GPGGA has coords near lat≈55.35, lon≈-132.516.
    // If it were accepted, a point with lat≈55.35 would appear.
    for (const p of pts) {
      expect(p.lat).toBeLessThan(55.35);
    }
  });

  it("accepts GPRMC sentences as a position source alongside GPGGA", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    // GPRMC pairs produce 2 depth points at depths 2400 and 2600 m.
    const rmc = pts.filter((p) => p.depth === 2400 || p.depth === 2600);
    expect(rmc.length).toBe(2);
  });

  it("reuses the most recent valid position when a malformed sentence is skipped", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    // The final SDDBT (depth=2700) is emitted after a malformed GPGGA.
    // Parser must use the last valid GPRMC position (lat≈55.209) for that point.
    const finalPt = pts.find((p) => p.depth === 2700);
    expect(finalPt).toBeDefined();
    expect(finalPt!.lat).toBeGreaterThanOrEqual(55.208);
    expect(finalPt!.lat).toBeLessThanOrEqual(55.21);
  });

  it("covers the expected geographic region (US Pacific coast survey area)", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    for (const p of pts) {
      expect(p.lon).toBeGreaterThanOrEqual(-132.52);
      expect(p.lon).toBeLessThanOrEqual(-132.499);
      expect(p.lat).toBeGreaterThanOrEqual(55.199);
      expect(p.lat).toBeLessThanOrEqual(55.21);
    }
  });

  it("produces depth values spanning the fixture's survey range", () => {
    const pts = parseNmea(nmeaBuf.toString("utf8"));
    const depths = pts.map((p) => p.depth);
    // Range: 1200 m (first GPGGA+SDDBT) to 2700 m (final SDDBT)
    expect(Math.min(...depths)).toBeCloseTo(1200, 0);
    expect(Math.max(...depths)).toBeCloseTo(2700, 0);
  });

  it("routes through parseUploadedFile dispatcher for .nmea", async () => {
    const pts = await parseUploadedFile(nmeaBuf, "survey.nmea");
    assertValidBathyPoints(pts, 10);
    expect(pts.length).toBe(11);
  });
});

// ---------------------------------------------------------------------------
// Cross-format consistency checks
// ---------------------------------------------------------------------------

describe("Cross-format consistency", () => {
  it("all seven formats produce finite, positive depth values", async () => {
    const [tifPts, las12Pts, las14Pts, bagPts] = await Promise.all([
      parseGeoTiff(tifBuf),
      parseLasLaz(las12Buf, "survey_1_2.las"),
      parseLasLaz(las14Buf, "survey_1_4.las"),
      parseBag(bagBuf),
    ]);
    const ncPts = parseNetCdf(ncBuf);
    const gpxPts = parseGpxTerrain(gpxBuf.toString("utf8"));
    const nmeaPts = parseNmea(nmeaBuf.toString("utf8"));

    for (const pts of [tifPts, ncPts, las12Pts, las14Pts, bagPts, gpxPts, nmeaPts]) {
      expect(pts.length).toBeGreaterThan(0);
      for (const p of pts) {
        expect(p.depth).toBeGreaterThan(0);
        expect(Number.isFinite(p.depth)).toBe(true);
      }
    }
  });

  it("parseUploadedFile handles all seven fixture files without throwing", async () => {
    const results = await Promise.allSettled([
      parseUploadedFile(tifBuf, "survey.tif"),
      Promise.resolve(parseUploadedFile(ncBuf, "survey.nc")),
      parseUploadedFile(las12Buf, "survey_1_2.las"),
      parseUploadedFile(las14Buf, "survey_1_4.las"),
      parseUploadedFile(bagBuf, "survey.bag"),
      parseUploadedFile(gpxBuf, "survey.gpx"),
      parseUploadedFile(nmeaBuf, "survey.nmea"),
    ]);

    for (const r of results) {
      expect(r.status).toBe("fulfilled");
    }

    const pointCounts = results
      .filter((r): r is PromiseFulfilledResult<RawPoint[]> => r.status === "fulfilled")
      .map((r) => r.value.length);

    for (const count of pointCounts) {
      expect(count).toBeGreaterThanOrEqual(10);
    }
  });
});
