-- Migration: DB schema constraints & integrity
-- Adds unique constraints, check constraints, and foreign keys that were
-- previously missing, causing silent duplicate/invalid data at the DB level.
--
-- Data-cleanup steps run first so constraint creation never fails on
-- pre-existing rows.

-- ─── M-1: deduplicate user_catalog_saves before uniqueness index ─────────────
DELETE FROM "user_catalog_saves"
WHERE id IN (
  SELECT id FROM (
    SELECT id,
      ROW_NUMBER() OVER (PARTITION BY user_id, catalog_id ORDER BY requested_at ASC) AS rn
    FROM "user_catalog_saves"
  ) ranked
  WHERE rn > 1
);
--> statement-breakpoint

-- ─── M-2: deduplicate gps_trail_points before (trail_id, seq) index ──────────
DELETE FROM "gps_trail_points"
WHERE id IN (
  SELECT id FROM (
    SELECT id,
      ROW_NUMBER() OVER (PARTITION BY trail_id, seq ORDER BY id ASC) AS rn
    FROM "gps_trail_points"
  ) ranked
  WHERE rn > 1
);
--> statement-breakpoint

-- ─── M-3: deduplicate root folders before partial unique index ────────────────
DELETE FROM "dataset_folders"
WHERE parent_id IS NULL
  AND id IN (
    SELECT id FROM (
      SELECT id,
        ROW_NUMBER() OVER (
          PARTITION BY user_id, lower(name)
          ORDER BY created_at ASC
        ) AS rn
      FROM "dataset_folders"
      WHERE parent_id IS NULL
    ) ranked
    WHERE rn > 1
  );
--> statement-breakpoint

-- ─── L-3: nullify orphaned upload_jobs.dataset_id before FK ──────────────────
UPDATE "upload_jobs"
  SET dataset_id = NULL
  WHERE dataset_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM "custom_datasets" WHERE id = "upload_jobs".dataset_id
    );
--> statement-breakpoint

-- ─── L-3: sanitise gps_trails.dataset_id before type cast + FK ───────────────
-- Step 1: null out non-UUID strings so the cast cannot fail.
UPDATE "gps_trails"
  SET dataset_id = NULL
  WHERE dataset_id IS NOT NULL
    AND dataset_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
-- Step 2: null out valid-UUID but orphaned references.
UPDATE "gps_trails"
  SET dataset_id = NULL
  WHERE dataset_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM "custom_datasets" WHERE id::text = "gps_trails".dataset_id
    );
--> statement-breakpoint

-- ─── DDL (generated by drizzle-kit) ──────────────────────────────────────────
DROP INDEX "dataset_folders_unique_sibling_name";--> statement-breakpoint
ALTER TABLE "gps_trails" ALTER COLUMN "dataset_id" SET DATA TYPE uuid USING dataset_id::uuid;--> statement-breakpoint
ALTER TABLE "gps_trails" ALTER COLUMN "dataset_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "gps_trails" ADD CONSTRAINT "gps_trails_dataset_id_custom_datasets_id_fk" FOREIGN KEY ("dataset_id") REFERENCES "public"."custom_datasets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upload_jobs" ADD CONSTRAINT "upload_jobs_dataset_id_custom_datasets_id_fk" FOREIGN KEY ("dataset_id") REFERENCES "public"."custom_datasets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "dataset_folders_root_name_uniq" ON "dataset_folders" USING btree ("user_id",lower("name")) WHERE "dataset_folders"."parent_id" IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "dataset_folders_child_name_uniq" ON "dataset_folders" USING btree ("user_id","parent_id",lower("name")) WHERE "dataset_folders"."parent_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "gps_trail_points_trail_seq_uniq" ON "gps_trail_points" USING btree ("trail_id","seq");--> statement-breakpoint
CREATE UNIQUE INDEX "user_catalog_saves_user_catalog_uniq" ON "user_catalog_saves" USING btree ("user_id","catalog_id");--> statement-breakpoint
ALTER TABLE "upload_jobs" ADD CONSTRAINT "upload_jobs_status_check" CHECK ("upload_jobs"."status" IN ('uploading', 'queued', 'processing', 'done', 'error'));--> statement-breakpoint
ALTER TABLE "terrain_bundle_jobs" ADD CONSTRAINT "terrain_bundle_jobs_status_check" CHECK ("terrain_bundle_jobs"."status" IN ('pending', 'running', 'complete', 'error'));
