/**
 * build-tx-lake-substrate.ts — Build a real-geometry freshwater substrate
 * bundle for the Texas reservoir presets (Lake Fork, Sam Rayburn,
 * Lake Ray Roberts, Toledo Bend).
 *
 * Why this exists: the existing SE Alaska substrate bundles (Alaska
 * ShoreZone + NOAA ENC) don't cover freshwater Texas reservoirs, so the
 * zone classifier falls back to depth-only inference for those datasets.
 * This script ingests real lake-outline polygons from the USGS National
 * Hydrography Dataset (NHD Waterbody, FTYPE=390) and splits each lake
 * into two substrate zones using lake-bottom characterisations published
 * by Texas Parks & Wildlife (TPWD) and Texas Water Development Board
 * (TWDB) reservoir / volumetric surveys:
 *
 *   • Shoreline littoral belt  — sand / gravel
 *     (TPWD lake-survey reports describe these reservoirs as having
 *      gravel-to-sand littoral shorelines with submerged timber and
 *      crappie / bass spawning structure).
 *   • Main basin / inundated channels — mud
 *     (TWDB volumetric surveys document fine-sediment accumulation in
 *      the inundated river / creek channels and the deep basin.)
 *
 * The shoreline belt is generated by inward-buffering the NHD waterbody
 * outline by a per-lake distance (~150 m) and subtracting; the remainder
 * becomes the main-basin polygon. Both polygons are real-geometry slices
 * of the actual reservoir outline — no fabricated rectangles.
 *
 * Sources:
 *   - USGS National Hydrography Dataset — Waterbody (large scale, layer 12)
 *     https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/12
 *   - TPWD Inland Fisheries lake-survey reports (lake-bottom narratives):
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/fork/
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/samrayburn/
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/rayroberts/
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/toledobend/
 *   - TWDB Reservoir Volumetric & Sedimentation Surveys:
 *     https://www.twdb.texas.gov/surfacewater/surveys/index.asp
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run build-tx-lake-substrate
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const OUT_PATH = resolve(
  REPO_ROOT,
  "artifacts/api-server/src/lib/txLakeSubstrate.gen.json",
);

const NHD_WATERBODY =
  "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/12";

// ---------------------------------------------------------------------------
// Lake catalogue
// ---------------------------------------------------------------------------

interface LakeSpec {
  datasetId: string;
  region: string;
  bbox: [number, number, number, number];
  nhdLakeNames: string[];
  /** Inward-buffer width for the littoral shoreline belt, in metres. */
  litoralBeltMeters: number;
  /** TPWD lake-info page used as creditUrl. */
  lakePageUrl: string;
  /** One-line lake-bottom narrative (from TPWD / TWDB surveys). */
  bottomNarrative: string;
}

const LAKES: LakeSpec[] = [
  {
    datasetId: "lake-fork",
    region: "Lake Fork Reservoir — East Texas",
    bbox: [-95.65, 32.78, -95.42, 32.95],
    nhdLakeNames: ["Lake Fork Reservoir"],
    litoralBeltMeters: 120,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/fork/",
    bottomNarrative:
      "TPWD lake-survey reports: standing-timber flats with sand/gravel littoral shoreline; " +
      "deep basin and inundated Sabine-headwater channel are fine sediment.",
  },
  {
    datasetId: "sam-rayburn",
    region: "Sam Rayburn Reservoir — East Texas",
    bbox: [-94.30, 31.05, -93.95, 31.60],
    nhdLakeNames: ["Sam Rayburn Reservoir"],
    litoralBeltMeters: 200,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/samrayburn/",
    bottomNarrative:
      "TPWD/TWDB surveys: hydrilla-vegetated sandy-loam littoral shoreline; " +
      "Angelina River channel and main basin dominated by mud/clay deposition.",
  },
  {
    datasetId: "lake-ray-roberts",
    region: "Lake Ray Roberts — North Texas",
    bbox: [-97.15, 33.30, -96.92, 33.52],
    nhdLakeNames: ["Lake Ray Roberts", "Ray Roberts Lake"],
    litoralBeltMeters: 100,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/rayroberts/",
    bottomNarrative:
      "TPWD lake-survey: rocky/gravel littoral shoreline along Elm Fork " +
      "tributary; main basin is silt/clay from Trinity-River sediment load.",
  },
  {
    datasetId: "toledo-bend",
    region: "Toledo Bend Reservoir — Texas / Louisiana",
    bbox: [-93.95, 31.15, -93.55, 32.20],
    nhdLakeNames: ["Toledo Bend Reservoir"],
    litoralBeltMeters: 220,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/toledobend/",
    bottomNarrative:
      "TPWD/TWDB: gravel/sand littoral with standing timber; Sabine River " +
      "channel and basin floor are mud/clay (organic accumulation).",
  },
];

// ---------------------------------------------------------------------------
// Output schema (matches the SubstrateFeatureProperties shape consumed by
// artifacts/api-server/src/lib/shoreZoneData.ts; the freshwater bundle uses
// an extended SubstrateSource literal `"tpwd-tx-reservoirs"`.)
// ---------------------------------------------------------------------------

type CmecsClass = "bedrock" | "gravel" | "sand" | "mud";

const CMECS: Record<CmecsClass, string> = {
  bedrock: "2.1.1 Consolidated Mineral Substrate",
  gravel:  "2.2.1 Mixed Coarse Unconsolidated Substrate",
  sand:    "2.2.2 Sand",
  mud:     "2.2.4 Fine Unconsolidated Substrate",
};
const COLOR: Record<CmecsClass, string> = {
  bedrock: "#6b6b6b",
  gravel:  "#b0956a",
  sand:    "#e2d5a0",
  mud:     "#8b7355",
};

interface BundledProps {
  unitId: string;
  substrate: CmecsClass;
  shoreZoneClass: string;
  cmecsCode: string;
  color: string;
  source: "tpwd-tx-reservoirs";
  /** Free-text bottom-type narrative from the TPWD/TWDB source. */
  natsur: string;
  natqua: null;
  /** TPWD lake page url (used per-feature so the UI can link out). */
  encChart: string;
}

interface PolygonGeom { type: "Polygon"; coordinates: number[][][] }
interface MultiPolygonGeom { type: "MultiPolygon"; coordinates: number[][][][] }
type AnyPolygonGeom = PolygonGeom | MultiPolygonGeom;

interface BundledFeature {
  type: "Feature";
  properties: BundledProps;
  geometry: AnyPolygonGeom;
}

interface BundledCollection {
  type: "FeatureCollection";
  features: BundledFeature[];
  metadata: {
    region: string;
    bbox: [number, number, number, number];
    source: "tpwd-tx-reservoirs";
    sourceName: string;
    sourceLayer: string;
    sourceService: string;
    creditUrl: string;
    fetchedAt: string;
    featureCount: number;
  };
}

// ---------------------------------------------------------------------------
// Geometry helpers (lon/lat <-> local metres, simple inward buffer)
// ---------------------------------------------------------------------------

const METERS_PER_DEG_LAT = 111_320;
function metersPerDegLon(latDeg: number): number {
  return METERS_PER_DEG_LAT * Math.cos((latDeg * Math.PI) / 180);
}

interface XY { x: number; y: number }
function toLocal(lon: number, lat: number, originLat: number): XY {
  return { x: lon * metersPerDegLon(originLat), y: lat * METERS_PER_DEG_LAT };
}
function toLonLat(xy: XY, originLat: number): [number, number] {
  return [xy.x / metersPerDegLon(originLat), xy.y / METERS_PER_DEG_LAT];
}

/** Signed area in local metres (CCW positive). */
function ringArea(ring: XY[]): number {
  let a = 0;
  for (let i = 0, n = ring.length; i < n; i++) {
    const p = ring[i]!;
    const q = ring[(i + 1) % n]!;
    a += p.x * q.y - q.x * p.y;
  }
  return a / 2;
}

/**
 * Approximate inward buffer (erosion) of a simple polygon ring by `r`
 * metres. For each vertex we shift inward along the average of the two
 * incident-edge inward normals, scaled by 1/cos(half-angle) so straight
 * stretches end up exactly `r` away from the original edge. The result
 * is a coarser ring but is good enough to produce a recognisable
 * shoreline-belt vs main-basin split for visualisation and grounding.
 *
 * If the ring is too small to be eroded by `r`, returns an empty array.
 */
function erodeRing(ring: XY[], r: number): XY[] {
  if (ring.length < 4) return [];
  // Ensure CCW so the inward normal is consistent.
  const closed = ring[0]!.x === ring[ring.length - 1]!.x && ring[0]!.y === ring[ring.length - 1]!.y
    ? ring.slice(0, -1)
    : ring.slice();
  const ccw = ringArea(closed) > 0;
  const ordered = ccw ? closed : closed.slice().reverse();
  const n = ordered.length;
  const out: XY[] = [];
  for (let i = 0; i < n; i++) {
    const prev = ordered[(i - 1 + n) % n]!;
    const curr = ordered[i]!;
    const next = ordered[(i + 1) % n]!;
    const inAng = Math.atan2(curr.y - prev.y, curr.x - prev.x);
    const outAng = Math.atan2(next.y - curr.y, next.x - curr.x);
    // For CCW ring the inward normal of an edge with direction θ is θ - π/2.
    const nIn = inAng - Math.PI / 2;
    const nOut = outAng - Math.PI / 2;
    let diff = nOut - nIn;
    while (diff > Math.PI) diff -= 2 * Math.PI;
    while (diff < -Math.PI) diff += 2 * Math.PI;
    const mid = nIn + diff / 2;
    const scale = r / Math.max(0.25, Math.cos(diff / 2));
    out.push({ x: curr.x + scale * Math.cos(mid), y: curr.y + scale * Math.sin(mid) });
  }
  // Reject degenerate eroded rings.
  if (out.length < 4 || Math.abs(ringArea(out)) < r * r * 4) return [];
  return out;
}

// ---------------------------------------------------------------------------
// ArcGIS fetch
// ---------------------------------------------------------------------------

interface EsriPolygon { rings: number[][][] }
interface EsriFeature<G, A> { attributes: A; geometry: G }

async function arcgisQuery<T = unknown>(
  service: string,
  params: Record<string, string>,
): Promise<T> {
  const url = `${service}/query?${new URLSearchParams(params).toString()}`;
  const resp = await fetch(url, { signal: AbortSignal.timeout(120_000) });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} from ${url.slice(0, 200)}`);
  return (await resp.json()) as T;
}

async function fetchNhdWaterbody(spec: LakeSpec): Promise<EsriPolygon | null> {
  for (const name of spec.nhdLakeNames) {
    const fc = await arcgisQuery<{
      features: EsriFeature<EsriPolygon, { AREASQKM: number; GNIS_NAME: string }>[];
    }>(NHD_WATERBODY, {
      where: `GNIS_NAME='${name}' AND FTYPE=390 AND AREASQKM>5`,
      outFields: "AREASQKM,GNIS_NAME",
      outSR: "4326",
      returnGeometry: "true",
      f: "json",
    });
    if (fc.features.length > 0) {
      const biggest = fc.features.reduce((a, b) =>
        a.attributes.AREASQKM > b.attributes.AREASQKM ? a : b);
      console.log(`    NHD waterbody '${name}': ${biggest.attributes.AREASQKM.toFixed(1)} km²`);
      return biggest.geometry;
    }
  }
  // Fallback: largest waterbody in bbox.
  const [minLon, minLat, maxLon, maxLat] = spec.bbox;
  const fc = await arcgisQuery<{
    features: EsriFeature<EsriPolygon, { AREASQKM: number; GNIS_NAME: string }>[];
  }>(NHD_WATERBODY, {
    geometry: `${minLon},${minLat},${maxLon},${maxLat}`,
    geometryType: "esriGeometryEnvelope",
    inSR: "4326",
    spatialRel: "esriSpatialRelIntersects",
    where: "FTYPE=390 AND AREASQKM>10",
    outFields: "AREASQKM,GNIS_NAME",
    outSR: "4326",
    returnGeometry: "true",
    f: "json",
  });
  if (fc.features.length === 0) return null;
  const biggest = fc.features.reduce((a, b) =>
    a.attributes.AREASQKM > b.attributes.AREASQKM ? a : b);
  console.log(
    `    NHD waterbody fallback (largest in bbox): '${biggest.attributes.GNIS_NAME ?? "(none)"}' ${biggest.attributes.AREASQKM.toFixed(1)} km²`,
  );
  return biggest.geometry;
}

// ---------------------------------------------------------------------------
// Per-lake feature construction
// ---------------------------------------------------------------------------

function ringToLonLat(local: XY[], originLat: number): number[][] {
  const out = local.map((p) => toLonLat(p, originLat));
  if (out.length === 0) return [];
  const first = out[0]!;
  out.push([first[0], first[1]]);
  return out;
}

/**
 * Douglas–Peucker polyline simplification in local-metres coordinates.
 * Drops vertices whose perpendicular distance to the simplified line is
 * less than `toleranceMeters`. Critical for NHD waterbody polygons which
 * carry tens of thousands of vertices per shoreline — without
 * simplification the bundled JSON would be 40+ MB per lake.
 */
function simplifyLocal(points: XY[], toleranceMeters: number): XY[] {
  if (points.length < 3) return [...points];
  const sqTol = toleranceMeters * toleranceMeters;
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack: [number, number][] = [[0, points.length - 1]];
  const sqDistSeg = (p: XY, a: XY, b: XY): number => {
    let x = a.x, y = a.y;
    let dx = b.x - x, dy = b.y - y;
    if (dx !== 0 || dy !== 0) {
      const t = ((p.x - x) * dx + (p.y - y) * dy) / (dx * dx + dy * dy);
      if (t > 1) { x = b.x; y = b.y; }
      else if (t > 0) { x += dx * t; y += dy * t; }
    }
    dx = p.x - x; dy = p.y - y;
    return dx * dx + dy * dy;
  };
  while (stack.length > 0) {
    const [lo, hi] = stack.pop()!;
    let maxSq = 0, maxIdx = -1;
    for (let i = lo + 1; i < hi; i++) {
      const sq = sqDistSeg(points[i]!, points[lo]!, points[hi]!);
      if (sq > maxSq) { maxSq = sq; maxIdx = i; }
    }
    if (maxSq > sqTol && maxIdx >= 0) {
      keep[maxIdx] = 1;
      stack.push([lo, maxIdx], [maxIdx, hi]);
    }
  }
  const out: XY[] = [];
  for (let i = 0; i < points.length; i++) if (keep[i]) out.push(points[i]!);
  return out;
}

/** Simplification tolerance for shoreline rings, in metres. ~30 m matches
 *  the natural granularity of the resolved 32×32 classification grid for
 *  the Texas-reservoir AOIs and shrinks bundled JSON by ~99 %. */
const SIMPLIFY_TOLERANCE_M = 30;

function buildLakeFeatures(spec: LakeSpec, esri: EsriPolygon): BundledFeature[] {
  const originLat = (spec.bbox[1] + spec.bbox[3]) / 2;
  const outerLocalRings: XY[][] = [];
  for (const ring of esri.rings) {
    const local = ring.map(([lo, la]) => toLocal(lo!, la!, originLat));
    if (local.length < 4) continue;
    const simplified = simplifyLocal(local, SIMPLIFY_TOLERANCE_M);
    if (simplified.length >= 4) outerLocalRings.push(simplified);
  }
  if (outerLocalRings.length === 0) return [];

  const mainBasinPolys: number[][][][] = [];
  const littoralPolys: number[][][][] = [];
  for (const outer of outerLocalRings) {
    const eroded = erodeRing(outer, spec.litoralBeltMeters);
    const outerLonLat = ringToLonLat(outer, originLat);
    if (eroded.length === 0) {
      // Lake is too small to split — classify entire footprint as littoral.
      littoralPolys.push([outerLonLat]);
      continue;
    }
    const erodedLonLat = ringToLonLat(eroded, originLat);
    // Main basin = inner polygon (erosion result).
    mainBasinPolys.push([erodedLonLat]);
    // Littoral belt = outer with eroded as a hole.
    littoralPolys.push([outerLonLat, erodedLonLat.slice().reverse()]);
  }

  const out: BundledFeature[] = [];
  const baseProps = (
    substrate: CmecsClass,
    label: string,
    suffix: string,
  ): BundledProps => ({
    unitId: `${spec.datasetId}-${suffix}`,
    substrate,
    shoreZoneClass: label,
    cmecsCode: CMECS[substrate],
    color: COLOR[substrate],
    source: "tpwd-tx-reservoirs",
    natsur: spec.bottomNarrative,
    natqua: null,
    encChart: spec.lakePageUrl,
  });
  if (mainBasinPolys.length === 1) {
    out.push({
      type: "Feature",
      properties: baseProps("mud", "Main basin / inundated channels (mud/clay)", "basin"),
      geometry: { type: "Polygon", coordinates: mainBasinPolys[0]! },
    });
  } else if (mainBasinPolys.length > 1) {
    out.push({
      type: "Feature",
      properties: baseProps("mud", "Main basin / inundated channels (mud/clay)", "basin"),
      geometry: { type: "MultiPolygon", coordinates: mainBasinPolys },
    });
  }
  if (littoralPolys.length === 1) {
    out.push({
      type: "Feature",
      properties: baseProps("sand", "Littoral shoreline belt (sand/gravel)", "littoral"),
      geometry: { type: "Polygon", coordinates: littoralPolys[0]! },
    });
  } else if (littoralPolys.length > 1) {
    out.push({
      type: "Feature",
      properties: baseProps("sand", "Littoral shoreline belt (sand/gravel)", "littoral"),
      geometry: { type: "MultiPolygon", coordinates: littoralPolys },
    });
  }
  return out;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("=== build-tx-lake-substrate ===");
  const allFeatures: BundledFeature[] = [];
  let bbox: [number, number, number, number] = [
    Infinity, Infinity, -Infinity, -Infinity,
  ];
  for (const spec of LAKES) {
    console.log(`  ${spec.datasetId}: fetching NHD waterbody…`);
    const lake = await fetchNhdWaterbody(spec);
    if (!lake) {
      console.warn(`    no NHD waterbody found for ${spec.datasetId} — skipping`);
      continue;
    }
    const feats = buildLakeFeatures(spec, lake);
    console.log(`    built ${feats.length} substrate feature(s)`);
    allFeatures.push(...feats);
    bbox = [
      Math.min(bbox[0], spec.bbox[0]),
      Math.min(bbox[1], spec.bbox[1]),
      Math.max(bbox[2], spec.bbox[2]),
      Math.max(bbox[3], spec.bbox[3]),
    ];
  }
  const counts: Record<string, number> = {};
  for (const f of allFeatures) counts[f.properties.substrate] = (counts[f.properties.substrate] ?? 0) + 1;
  console.log(`  Bundled: ${allFeatures.length} features; distribution ${JSON.stringify(counts)}`);

  const bundle: BundledCollection = {
    type: "FeatureCollection",
    features: allFeatures,
    metadata: {
      region:
        "Texas freshwater reservoirs (Lake Fork, Sam Rayburn, Ray Roberts, Toledo Bend) — NHD outline + TPWD/TWDB substrate",
      bbox,
      source: "tpwd-tx-reservoirs",
      sourceName:
        "USGS NHD Waterbody outlines classified by TPWD Inland Fisheries lake-survey reports and TWDB volumetric/sedimentation surveys",
      sourceLayer: "NHD MapServer/12 (Waterbody) + TPWD lake-bottom narratives",
      sourceService: NHD_WATERBODY,
      creditUrl:
        "https://tpwd.texas.gov/fishing/freshwater-fishing/where-to-fish/freshwater-lakes/",
      fetchedAt: new Date().toISOString(),
      featureCount: allFeatures.length,
    },
  };

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, JSON.stringify(bundle), "utf8");
  console.log(`  Wrote ${OUT_PATH}`);
  console.log("=== done ===");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
