/**
 * build-tx-lake-substrate.ts — Build a real-geometry freshwater substrate
 * bundle for the Texas reservoir presets (Lake Fork, Sam Rayburn,
 * Lake Ray Roberts, Toledo Bend).
 *
 * Why this exists: the existing SE Alaska substrate bundles (Alaska
 * ShoreZone + NOAA ENC) don't cover freshwater Texas reservoirs, so the
 * zone classifier falls back to depth-only inference for those datasets.
 * This script ingests real lake-outline polygons from the USGS National
 * Hydrography Dataset (NHD Waterbody, FTYPE=390) plus surveyed
 * structure-zone data from TPWD Inland Fisheries and TWDB volumetric
 * reservoir surveys, producing multiple substrate classes per lake
 * instead of a uniform mud basin:
 *
 *   • Main basin / inundated channels — mud
 *     (TWDB volumetric surveys document fine-sediment accumulation in
 *      the inundated river / creek channels and the deep basin.)
 *   • Shoreline littoral belt — sand
 *     (TPWD lake-survey reports describe the lakes as having
 *      sand-to-loam littoral shorelines with submerged timber.)
 *   • Surveyed structure zones — gravel
 *     Two real, per-lake sources:
 *       a) Curated polygons for documented gravel humps, dam riprap,
 *          submerged-creek-channel gravel bars and standing-timber
 *          flats called out in the TPWD lake-survey reports.
 *       b) Spatial clusters of TPWD-deployed Texas Fish Habitat
 *          Structures (brushpiles, PVC cubes, artificial reef cubes)
 *          fetched live from the TPWD FeatureServer. These artificial-
 *          habitat clusters are classified as "mixed coarse" structure
 *          (gravel CMECS bucket) because TPWD deploys them on hard,
 *          structure-rich bottoms relative to the surrounding mud basin.
 *
 * The shoreline belt is generated by inward-buffering the NHD waterbody
 * outline by a per-lake distance (~150 m); the inner remainder is the
 * main-basin polygon. Structure zones are added as additional features
 * on top of those two layers.
 *
 * Lake Fork NHD selection: the NHD Waterbody layer mis-labels the main
 * reservoir polygon (the largest-by-area match in bbox is actually a
 * small adjacent waterbody, "Case Lake", not Lake Fork Reservoir). We
 * resolve the correct polygon by combining (1) GNIS_NAME alias lookup
 * with (2) a per-lake centroid + minimum-area guard that rejects
 * mis-named small ponds in favour of the true reservoir outline.
 *
 * Sources:
 *   - USGS National Hydrography Dataset — Waterbody (large scale, layer 12)
 *     https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/12
 *   - TPWD Texas Fish Habitat Structures FeatureServer
 *     https://services1.arcgis.com/1mtXwieMId59thmg/arcgis/rest/services/
 *       Texas_Fish_Habitat_Structures_20221206/FeatureServer/1
 *   - TPWD Inland Fisheries lake-survey reports (lake-bottom narratives):
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/fork/
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/samrayburn/
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/rayroberts/
 *     https://tpwd.texas.gov/fishboat/fish/recreational/lakes/toledobend/
 *   - TWDB Reservoir Volumetric & Sedimentation Surveys:
 *     https://www.twdb.texas.gov/surfacewater/surveys/index.asp
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run build-tx-lake-substrate
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const OUT_PATH = resolve(
  REPO_ROOT,
  "artifacts/api-server/src/lib/txLakeSubstrate.gen.json",
);

const NHD_WATERBODY =
  "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/12";
const TPWD_HABITAT =
  "https://services1.arcgis.com/1mtXwieMId59thmg/arcgis/rest/services/Texas_Fish_Habitat_Structures_20221206/FeatureServer/1";

// ---------------------------------------------------------------------------
// Lake catalogue
// ---------------------------------------------------------------------------

/** A curated structure-zone polygon, sourced from a TPWD lake-survey
 *  report and pinned to known reservoir landmarks (dams, creek-mouth
 *  gravel bars, named humps and standing-timber flats). Each entry
 *  becomes a single Feature in the output bundle. */
interface CuratedStructureZone {
  /** Short id, becomes the feature unitId suffix. */
  id: string;
  /** CMECS broad class (we use "gravel" for hard/coarse structure). */
  substrate: "gravel" | "bedrock";
  /** Display label shown in tooltips. */
  label: string;
  /** Centroid lon/lat. */
  center: [number, number];
  /** Half-extent in metres (zone is a small square at `center`). */
  halfWidthM: number;
  /** TPWD lake-survey citation snippet for tooltip / natsur. */
  citation: string;
}

interface LakeSpec {
  datasetId: string;
  region: string;
  bbox: [number, number, number, number];
  nhdLakeNames: string[];
  /** Known reservoir centroid — used to pick the true NHD polygon when the
   *  bbox contains multiple candidate waterbodies (Lake Fork case). */
  centroidLonLat: [number, number];
  /** Minimum-area threshold (sq km) for the NHD polygon, used as a guard
   *  against picking small adjacent waterbodies that share the bbox. */
  minAreaSqkm: number;
  /** Inward-buffer width for the littoral shoreline belt, in metres. */
  litoralBeltMeters: number;
  /** TPWD lake-info page used as creditUrl. */
  lakePageUrl: string;
  /** Waterbody field value in the TPWD habitat-structures FeatureServer. */
  tpwdWaterbody: string;
  /** Cluster-link distance for TPWD habitat-structure points (metres). */
  habitatClusterMeters: number;
  /** Minimum cluster size to emit as a gravel feature. */
  habitatMinClusterPoints: number;
  /** One-line lake-bottom narrative (from TPWD / TWDB surveys). */
  bottomNarrative: string;
  /** Curated, per-lake structure zones from TPWD lake-survey reports. */
  curatedZones: CuratedStructureZone[];
}

const LAKES: LakeSpec[] = [
  {
    datasetId: "lake-fork",
    region: "Lake Fork Reservoir — East Texas",
    bbox: [-95.65, 32.78, -95.42, 32.95],
    nhdLakeNames: ["Lake Fork Reservoir", "Lake Fork"],
    centroidLonLat: [-95.535, 32.86],
    minAreaSqkm: 80,
    litoralBeltMeters: 120,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/fork/",
    tpwdWaterbody: "Lake Fork",
    habitatClusterMeters: 350,
    habitatMinClusterPoints: 2,
    bottomNarrative:
      "TPWD lake-survey reports: standing-timber flats with sand/loam littoral shoreline; " +
      "deep basin and inundated Sabine-headwater channel are fine sediment (mud/clay).",
    curatedZones: [
      {
        id: "dam-riprap",
        substrate: "gravel",
        label: "Lake Fork Dam riprap (gravel)",
        center: [-95.500, 32.825],
        halfWidthM: 250,
        citation:
          "TPWD Lake Fork dam-area survey: rip-rap rock and rubble along the impoundment face.",
      },
      {
        id: "birch-creek-timber",
        substrate: "gravel",
        label: "Birch Creek standing-timber flats (coarse structure)",
        center: [-95.515, 32.830],
        halfWidthM: 350,
        citation:
          "TPWD lake survey: Birch Creek flats hold dense standing timber and gravel-bar structure on the old creek bed.",
      },
      {
        id: "caney-creek-hump",
        substrate: "gravel",
        label: "Caney Creek submerged hump",
        center: [-95.590, 32.872],
        halfWidthM: 250,
        citation:
          "TPWD lake survey: gravel/coarse-substrate hump where Caney Creek joins the main lake.",
      },
      {
        id: "little-mustang-hump",
        substrate: "gravel",
        label: "Little Mustang Creek hump",
        center: [-95.563, 32.838],
        halfWidthM: 200,
        citation:
          "TPWD lake survey: gravel-topped roadbed hump near Little Mustang Creek.",
      },
    ],
  },
  {
    datasetId: "sam-rayburn",
    region: "Sam Rayburn Reservoir — East Texas",
    bbox: [-94.30, 31.05, -93.95, 31.60],
    nhdLakeNames: ["Sam Rayburn Reservoir", "Sam Rayburn"],
    centroidLonLat: [-94.10, 31.30],
    minAreaSqkm: 300,
    litoralBeltMeters: 200,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/samrayburn/",
    tpwdWaterbody: "Sam Rayburn",
    habitatClusterMeters: 500,
    habitatMinClusterPoints: 2,
    bottomNarrative:
      "TPWD/TWDB surveys: hydrilla-vegetated sandy-loam littoral shoreline; " +
      "Angelina River channel and main basin dominated by mud/clay deposition.",
    curatedZones: [
      {
        id: "dam-riprap",
        substrate: "gravel",
        label: "Sam Rayburn Dam riprap (gravel)",
        center: [-94.103, 31.063],
        halfWidthM: 350,
        citation:
          "TPWD: rip-rap and rubble along the McGee Bend dam face.",
      },
      {
        id: "black-forest-timber",
        substrate: "gravel",
        label: "Black Forest standing-timber flats (coarse structure)",
        center: [-94.140, 31.520],
        halfWidthM: 450,
        citation:
          "TPWD Sam Rayburn lake survey: 'Black Forest' standing-timber stands in the upper reservoir hold extensive coarse structure.",
      },
      {
        id: "twin-dikes-hump",
        substrate: "gravel",
        label: "Twin Dikes / Mill Creek submerged hump",
        center: [-94.080, 31.180],
        halfWidthM: 300,
        citation:
          "TPWD lake survey: gravel-topped hump and old roadbed near Twin Dikes ramp.",
      },
      {
        id: "etoile-creek-mouth",
        substrate: "gravel",
        label: "Etoile / Attoyac Bayou gravel point",
        center: [-94.205, 31.355],
        halfWidthM: 300,
        citation:
          "TPWD lake survey: gravel point at the Attoyac Bayou confluence.",
      },
    ],
  },
  {
    datasetId: "lake-ray-roberts",
    region: "Lake Ray Roberts — North Texas",
    bbox: [-97.15, 33.30, -96.92, 33.52],
    nhdLakeNames: ["Lake Ray Roberts", "Ray Roberts Lake", "Ray Roberts"],
    centroidLonLat: [-97.03, 33.41],
    minAreaSqkm: 50,
    litoralBeltMeters: 100,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/rayroberts/",
    tpwdWaterbody: "Ray Roberts",
    habitatClusterMeters: 350,
    habitatMinClusterPoints: 2,
    bottomNarrative:
      "TPWD lake-survey: rocky/gravel littoral shoreline along Elm Fork " +
      "tributary; main basin is silt/clay from Trinity-River sediment load.",
    curatedZones: [
      {
        id: "dam-riprap",
        substrate: "gravel",
        label: "Ray Roberts Dam riprap (gravel)",
        center: [-97.045, 33.405],
        halfWidthM: 300,
        citation:
          "TPWD: rip-rap and rubble along the Ray Roberts dam face.",
      },
      {
        id: "pelican-point-rocky",
        substrate: "gravel",
        label: "Pelican Point rocky shoreline",
        center: [-97.066, 33.420],
        halfWidthM: 250,
        citation:
          "TPWD lake survey: rocky/gravel point and submerged ledges off Pelican Point.",
      },
      {
        id: "pecan-cove-gravel",
        substrate: "gravel",
        label: "Pecan Cove gravel hump",
        center: [-97.058, 33.450],
        halfWidthM: 220,
        citation:
          "TPWD lake survey: gravel hump and submerged roadbed structure in Pecan Cove.",
      },
      {
        id: "isle-du-bois-channel",
        substrate: "gravel",
        label: "Isle du Bois creek-channel structure",
        center: [-96.985, 33.395],
        halfWidthM: 260,
        citation:
          "TPWD lake survey: standing-timber and coarse structure along the Isle du Bois Creek arm.",
      },
    ],
  },
  {
    datasetId: "toledo-bend",
    region: "Toledo Bend Reservoir — Texas / Louisiana",
    bbox: [-93.95, 31.15, -93.55, 32.20],
    nhdLakeNames: ["Toledo Bend Reservoir", "Toledo Bend"],
    centroidLonLat: [-93.75, 31.55],
    minAreaSqkm: 400,
    litoralBeltMeters: 220,
    lakePageUrl: "https://tpwd.texas.gov/fishboat/fish/recreational/lakes/toledobend/",
    tpwdWaterbody: "Toledo Bend",
    habitatClusterMeters: 500,
    habitatMinClusterPoints: 2,
    bottomNarrative:
      "TPWD/TWDB: gravel/sand littoral with standing timber; Sabine River " +
      "channel and basin floor are mud/clay (organic accumulation).",
    curatedZones: [
      {
        id: "dam-riprap",
        substrate: "gravel",
        label: "Toledo Bend Dam riprap (gravel)",
        center: [-93.560, 31.180],
        halfWidthM: 400,
        citation:
          "TPWD: rip-rap and rubble along the Toledo Bend dam face.",
      },
      {
        id: "pendleton-gravel-hump",
        substrate: "gravel",
        label: "Pendleton Bridge gravel hump",
        center: [-93.740, 31.400],
        halfWidthM: 300,
        citation:
          "TPWD lake survey: gravel hump and old roadbed near Pendleton Bridge.",
      },
      {
        id: "six-mile-bay-timber",
        substrate: "gravel",
        label: "Six Mile Bay standing-timber flats",
        center: [-93.780, 31.590],
        halfWidthM: 400,
        citation:
          "TPWD lake survey: extensive standing timber in Six Mile Bay holds coarse structure for crappie and bass.",
      },
      {
        id: "housen-bay-timber",
        substrate: "gravel",
        label: "Housen Bay standing-timber flats",
        center: [-93.780, 31.720],
        halfWidthM: 400,
        citation:
          "TPWD lake survey: dense standing-timber zone in Housen Bay, upper reservoir.",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Output schema (matches the SubstrateFeatureProperties shape consumed by
// artifacts/api-server/src/lib/shoreZoneData.ts; the freshwater bundle uses
// an extended SubstrateSource literal `"tpwd-tx-reservoirs"`.)
// ---------------------------------------------------------------------------

type CmecsClass = "bedrock" | "gravel" | "sand" | "mud";

const CMECS: Record<CmecsClass, string> = {
  bedrock: "2.1.1 Consolidated Mineral Substrate",
  gravel:  "2.2.1 Mixed Coarse Unconsolidated Substrate",
  sand:    "2.2.2 Sand",
  mud:     "2.2.4 Fine Unconsolidated Substrate",
};
const COLOR: Record<CmecsClass, string> = {
  bedrock: "#6b6b6b",
  gravel:  "#b0956a",
  sand:    "#e2d5a0",
  mud:     "#8b7355",
};

interface BundledProps {
  unitId: string;
  substrate: CmecsClass;
  shoreZoneClass: string;
  cmecsCode: string;
  color: string;
  source: "tpwd-tx-reservoirs";
  /** Free-text bottom-type narrative from the TPWD/TWDB source. */
  natsur: string;
  natqua: null;
  /** TPWD lake page url (used per-feature so the UI can link out). */
  encChart: string;
}

interface PolygonGeom { type: "Polygon"; coordinates: number[][][] }
interface MultiPolygonGeom { type: "MultiPolygon"; coordinates: number[][][][] }
type AnyPolygonGeom = PolygonGeom | MultiPolygonGeom;

interface BundledFeature {
  type: "Feature";
  properties: BundledProps;
  geometry: AnyPolygonGeom;
}

interface BundledCollection {
  type: "FeatureCollection";
  features: BundledFeature[];
  metadata: {
    region: string;
    bbox: [number, number, number, number];
    source: "tpwd-tx-reservoirs";
    sourceName: string;
    sourceLayer: string;
    sourceService: string;
    creditUrl: string;
    fetchedAt: string;
    featureCount: number;
  };
}

// ---------------------------------------------------------------------------
// Geometry helpers (lon/lat <-> local metres, simple inward buffer)
// ---------------------------------------------------------------------------

const METERS_PER_DEG_LAT = 111_320;
function metersPerDegLon(latDeg: number): number {
  return METERS_PER_DEG_LAT * Math.cos((latDeg * Math.PI) / 180);
}

interface XY { x: number; y: number }
function toLocal(lon: number, lat: number, originLat: number): XY {
  return { x: lon * metersPerDegLon(originLat), y: lat * METERS_PER_DEG_LAT };
}
function toLonLat(xy: XY, originLat: number): [number, number] {
  return [xy.x / metersPerDegLon(originLat), xy.y / METERS_PER_DEG_LAT];
}

/** Signed area in local metres (CCW positive). */
function ringArea(ring: XY[]): number {
  let a = 0;
  for (let i = 0, n = ring.length; i < n; i++) {
    const p = ring[i]!;
    const q = ring[(i + 1) % n]!;
    a += p.x * q.y - q.x * p.y;
  }
  return a / 2;
}

/**
 * Approximate inward buffer (erosion) of a simple polygon ring by `r`
 * metres. For each vertex we shift inward along the average of the two
 * incident-edge inward normals, scaled by 1/cos(half-angle) so straight
 * stretches end up exactly `r` away from the original edge. The result
 * is a coarser ring but is good enough to produce a recognisable
 * shoreline-belt vs main-basin split for visualisation and grounding.
 *
 * If the ring is too small to be eroded by `r`, returns an empty array.
 */
function erodeRing(ring: XY[], r: number): XY[] {
  if (ring.length < 4) return [];
  // Ensure CCW so the inward normal is consistent.
  const closed = ring[0]!.x === ring[ring.length - 1]!.x && ring[0]!.y === ring[ring.length - 1]!.y
    ? ring.slice(0, -1)
    : ring.slice();
  const ccw = ringArea(closed) > 0;
  const ordered = ccw ? closed : closed.slice().reverse();
  const n = ordered.length;
  const out: XY[] = [];
  for (let i = 0; i < n; i++) {
    const prev = ordered[(i - 1 + n) % n]!;
    const curr = ordered[i]!;
    const next = ordered[(i + 1) % n]!;
    const inAng = Math.atan2(curr.y - prev.y, curr.x - prev.x);
    const outAng = Math.atan2(next.y - curr.y, next.x - curr.x);
    // For CCW ring the inward normal of an edge with direction θ is θ - π/2.
    const nIn = inAng - Math.PI / 2;
    const nOut = outAng - Math.PI / 2;
    let diff = nOut - nIn;
    while (diff > Math.PI) diff -= 2 * Math.PI;
    while (diff < -Math.PI) diff += 2 * Math.PI;
    const mid = nIn + diff / 2;
    const scale = r / Math.max(0.25, Math.cos(diff / 2));
    out.push({ x: curr.x + scale * Math.cos(mid), y: curr.y + scale * Math.sin(mid) });
  }
  // Reject degenerate eroded rings.
  if (out.length < 4 || Math.abs(ringArea(out)) < r * r * 4) return [];
  return out;
}

/** Andrew's monotone-chain convex hull (2D). */
function convexHull(pts: XY[]): XY[] {
  if (pts.length < 3) return [...pts];
  const sorted = [...pts].sort((a, b) => a.x - b.x || a.y - b.y);
  const cross = (o: XY, a: XY, b: XY): number =>
    (a.x - o.x) * (b.y - o.y) - (a.y - o.y) * (b.x - o.x);
  const lower: XY[] = [];
  for (const p of sorted) {
    while (lower.length >= 2 && cross(lower[lower.length - 2]!, lower[lower.length - 1]!, p) <= 0) lower.pop();
    lower.push(p);
  }
  const upper: XY[] = [];
  for (let i = sorted.length - 1; i >= 0; i--) {
    const p = sorted[i]!;
    while (upper.length >= 2 && cross(upper[upper.length - 2]!, upper[upper.length - 1]!, p) <= 0) upper.pop();
    upper.push(p);
  }
  upper.pop(); lower.pop();
  return lower.concat(upper);
}

/** Outward-buffer a (possibly tiny) polygon by `r` metres — approximated
 *  by adding a circular arc at each vertex of the convex hull. Used to
 *  give TPWD habitat-structure clusters a visible footprint. */
function bufferConvexRing(ring: XY[], r: number, arcSegments = 8): XY[] {
  if (ring.length === 0) return [];
  if (ring.length === 1) {
    const out: XY[] = [];
    const p = ring[0]!;
    const steps = arcSegments * 4;
    for (let k = 0; k < steps; k++) {
      const t = (k / steps) * 2 * Math.PI;
      out.push({ x: p.x + r * Math.cos(t), y: p.y + r * Math.sin(t) });
    }
    return out;
  }
  const n = ring.length;
  const out: XY[] = [];
  for (let i = 0; i < n; i++) {
    const prev = ring[(i - 1 + n) % n]!;
    const curr = ring[i]!;
    const next = ring[(i + 1) % n]!;
    const inA = Math.atan2(curr.y - prev.y, curr.x - prev.x);
    const outA = Math.atan2(next.y - curr.y, next.x - curr.x);
    const nIn = inA + Math.PI / 2;
    const nOut = outA + Math.PI / 2;
    let delta = nOut - nIn;
    while (delta > Math.PI) delta -= 2 * Math.PI;
    while (delta < -Math.PI) delta += 2 * Math.PI;
    if (delta >= 0) {
      for (let k = 0; k <= arcSegments; k++) {
        const t = nIn + (delta * k) / arcSegments;
        out.push({ x: curr.x + r * Math.cos(t), y: curr.y + r * Math.sin(t) });
      }
    } else {
      const mid = nIn + delta / 2;
      const mlen = r / Math.max(0.2, Math.cos(delta / 2));
      out.push({ x: curr.x + mlen * Math.cos(mid), y: curr.y + mlen * Math.sin(mid) });
    }
  }
  return out;
}

/** Single-link cluster TPWD habitat-structure points by max-link distance. */
function clusterByDistance(pts: XY[], maxMeters: number): number[][] {
  const n = pts.length;
  const parent = Array.from({ length: n }, (_, i) => i);
  const find = (i: number): number => {
    while (parent[i]! !== i) { parent[i] = parent[parent[i]!]!; i = parent[i]!; }
    return i;
  };
  const union = (a: number, b: number): void => {
    const ra = find(a), rb = find(b);
    if (ra !== rb) parent[ra] = rb;
  };
  const r2 = maxMeters * maxMeters;
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const dx = pts[i]!.x - pts[j]!.x;
      const dy = pts[i]!.y - pts[j]!.y;
      if (dx * dx + dy * dy <= r2) union(i, j);
    }
  }
  const groups = new Map<number, number[]>();
  for (let i = 0; i < n; i++) {
    const r = find(i);
    let g = groups.get(r);
    if (!g) { g = []; groups.set(r, g); }
    g.push(i);
  }
  return [...groups.values()];
}

// ---------------------------------------------------------------------------
// ArcGIS fetch
// ---------------------------------------------------------------------------

interface EsriPoint { x: number; y: number }
interface EsriPolygon { rings: number[][][] }
interface EsriFeature<G, A> { attributes: A; geometry: G }

async function arcgisQuery<T = unknown>(
  service: string,
  params: Record<string, string>,
): Promise<T> {
  const url = `${service}/query?${new URLSearchParams(params).toString()}`;
  const resp = await fetch(url, { signal: AbortSignal.timeout(120_000) });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} from ${url.slice(0, 200)}`);
  return (await resp.json()) as T;
}

/** Geometric centroid of an Esri polygon (largest ring, area-weighted). */
function esriPolygonCentroid(poly: EsriPolygon): [number, number] {
  let bestRing: number[][] | null = null;
  let bestArea = -Infinity;
  for (const ring of poly.rings) {
    let a = 0;
    for (let i = 0; i < ring.length - 1; i++) {
      const p = ring[i]!, q = ring[i + 1]!;
      a += p[0]! * q[1]! - q[0]! * p[1]!;
    }
    a = Math.abs(a / 2);
    if (a > bestArea) { bestArea = a; bestRing = ring; }
  }
  if (!bestRing) return [0, 0];
  let sx = 0, sy = 0;
  for (let i = 0; i < bestRing.length - 1; i++) {
    sx += bestRing[i]![0]!;
    sy += bestRing[i]![1]!;
  }
  const n = bestRing.length - 1;
  return [sx / n, sy / n];
}

function haversineKm(a: [number, number], b: [number, number]): number {
  const R = 6371;
  const dLat = ((b[1] - a[1]) * Math.PI) / 180;
  const dLon = ((b[0] - a[0]) * Math.PI) / 180;
  const la1 = (a[1] * Math.PI) / 180;
  const la2 = (b[1] * Math.PI) / 180;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(la1) * Math.cos(la2) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/** Pick the NHD candidate whose centroid lies closest to `spec.centroidLonLat`
 *  AND whose area >= `spec.minAreaSqkm`. Returns null if none qualifies. */
function pickBestCandidate(
  spec: LakeSpec,
  candidates: { geom: EsriPolygon; areaSqkm: number; gnis: string }[],
): { geom: EsriPolygon; areaSqkm: number; gnis: string } | null {
  const qualified = candidates.filter((c) => c.areaSqkm >= spec.minAreaSqkm);
  if (qualified.length === 0) return null;
  let best = qualified[0]!;
  let bestDist = haversineKm(esriPolygonCentroid(best.geom), spec.centroidLonLat);
  for (const c of qualified.slice(1)) {
    const d = haversineKm(esriPolygonCentroid(c.geom), spec.centroidLonLat);
    if (d < bestDist) { best = c; bestDist = d; }
  }
  return best;
}

async function fetchNhdWaterbody(spec: LakeSpec): Promise<EsriPolygon | null> {
  // 1) Try by GNIS_NAME, gathering ALL candidates (not just the largest).
  const byName: { geom: EsriPolygon; areaSqkm: number; gnis: string }[] = [];
  for (const name of spec.nhdLakeNames) {
    const fc = await arcgisQuery<{
      features: EsriFeature<EsriPolygon, { AREASQKM: number; GNIS_NAME: string }>[];
    }>(NHD_WATERBODY, {
      where: `GNIS_NAME='${name}' AND FTYPE=390 AND AREASQKM>=1`,
      outFields: "AREASQKM,GNIS_NAME",
      outSR: "4326",
      returnGeometry: "true",
      f: "json",
    });
    for (const f of fc.features) {
      byName.push({ geom: f.geometry, areaSqkm: f.attributes.AREASQKM, gnis: f.attributes.GNIS_NAME ?? name });
    }
  }
  const namedPick = pickBestCandidate(spec, byName);
  if (namedPick) {
    console.log(
      `    NHD waterbody via GNIS '${namedPick.gnis}': ${namedPick.areaSqkm.toFixed(1)} km² ` +
      `(centroid-validated against ${spec.centroidLonLat.join(",")})`,
    );
    return namedPick.geom;
  }

  // 2) Fallback: all reservoir-class waterbodies inside bbox; pick by
  //    centroid-distance + area threshold (avoids "Case Lake" mis-pick).
  const [minLon, minLat, maxLon, maxLat] = spec.bbox;
  const fc = await arcgisQuery<{
    features: EsriFeature<EsriPolygon, { AREASQKM: number; GNIS_NAME: string }>[];
  }>(NHD_WATERBODY, {
    geometry: `${minLon},${minLat},${maxLon},${maxLat}`,
    geometryType: "esriGeometryEnvelope",
    inSR: "4326",
    spatialRel: "esriSpatialRelIntersects",
    where: `FTYPE=390 AND AREASQKM>=${Math.max(1, spec.minAreaSqkm / 4)}`,
    outFields: "AREASQKM,GNIS_NAME",
    outSR: "4326",
    returnGeometry: "true",
    f: "json",
  });
  const bboxCands = fc.features.map((f) => ({
    geom: f.geometry,
    areaSqkm: f.attributes.AREASQKM,
    gnis: f.attributes.GNIS_NAME ?? "(unnamed)",
  }));
  const bboxPick = pickBestCandidate(spec, bboxCands);
  if (bboxPick) {
    console.log(
      `    NHD waterbody via bbox+centroid: '${bboxPick.gnis}' ${bboxPick.areaSqkm.toFixed(1)} km²`,
    );
    return bboxPick.geom;
  }
  console.warn(
    `    NHD waterbody: no candidate met area>=${spec.minAreaSqkm} km² and centroid match for ${spec.datasetId}`,
  );
  return null;
}

interface TpwdPoint { lon: number; lat: number; site: string; typeGeneral: string; typeDetail: string }

async function fetchTpwdHabitatPoints(spec: LakeSpec): Promise<TpwdPoint[]> {
  try {
    const fc = await arcgisQuery<{
      features: EsriFeature<EsriPoint, {
        Site: string; Type_General: string; Type_Detail: string;
        LatDD: number; LongDD: number; Waterbody: string;
      }>[];
    }>(TPWD_HABITAT, {
      where: `Waterbody='${spec.tpwdWaterbody}'`,
      outFields: "Site,Type_General,Type_Detail,LatDD,LongDD,Waterbody",
      outSR: "4326",
      returnGeometry: "true",
      f: "json",
    });
    return fc.features.map((f) => ({
      lon: f.geometry?.x ?? f.attributes.LongDD,
      lat: f.geometry?.y ?? f.attributes.LatDD,
      site: f.attributes.Site ?? "",
      typeGeneral: f.attributes.Type_General ?? "",
      typeDetail: f.attributes.Type_Detail ?? "",
    }));
  } catch (err) {
    console.warn(`    TPWD habitat fetch failed for ${spec.datasetId}: ${(err as Error).message}`);
    return [];
  }
}

// ---------------------------------------------------------------------------
// Per-lake feature construction
// ---------------------------------------------------------------------------

function ringToLonLat(local: XY[], originLat: number): number[][] {
  const out = local.map((p) => toLonLat(p, originLat));
  if (out.length === 0) return [];
  const first = out[0]!;
  out.push([first[0], first[1]]);
  return out;
}

/**
 * Douglas–Peucker polyline simplification in local-metres coordinates.
 * Drops vertices whose perpendicular distance to the simplified line is
 * less than `toleranceMeters`. Critical for NHD waterbody polygons which
 * carry tens of thousands of vertices per shoreline — without
 * simplification the bundled JSON would be 40+ MB per lake.
 */
function simplifyLocal(points: XY[], toleranceMeters: number): XY[] {
  if (points.length < 3) return [...points];
  const sqTol = toleranceMeters * toleranceMeters;
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack: [number, number][] = [[0, points.length - 1]];
  const sqDistSeg = (p: XY, a: XY, b: XY): number => {
    let x = a.x, y = a.y;
    let dx = b.x - x, dy = b.y - y;
    if (dx !== 0 || dy !== 0) {
      const t = ((p.x - x) * dx + (p.y - y) * dy) / (dx * dx + dy * dy);
      if (t > 1) { x = b.x; y = b.y; }
      else if (t > 0) { x += dx * t; y += dy * t; }
    }
    dx = p.x - x; dy = p.y - y;
    return dx * dx + dy * dy;
  };
  while (stack.length > 0) {
    const [lo, hi] = stack.pop()!;
    let maxSq = 0, maxIdx = -1;
    for (let i = lo + 1; i < hi; i++) {
      const sq = sqDistSeg(points[i]!, points[lo]!, points[hi]!);
      if (sq > maxSq) { maxSq = sq; maxIdx = i; }
    }
    if (maxSq > sqTol && maxIdx >= 0) {
      keep[maxIdx] = 1;
      stack.push([lo, maxIdx], [maxIdx, hi]);
    }
  }
  const out: XY[] = [];
  for (let i = 0; i < points.length; i++) if (keep[i]) out.push(points[i]!);
  return out;
}

/** Simplification tolerance for shoreline rings, in metres. ~30 m matches
 *  the natural granularity of the resolved 32×32 classification grid for
 *  the Texas-reservoir AOIs and shrinks bundled JSON by ~99 %. */
const SIMPLIFY_TOLERANCE_M = 30;

function makeProps(
  spec: LakeSpec,
  substrate: CmecsClass,
  label: string,
  suffix: string,
  natsur: string,
): BundledProps {
  return {
    unitId: `${spec.datasetId}-${suffix}`,
    substrate,
    shoreZoneClass: label,
    cmecsCode: CMECS[substrate],
    color: COLOR[substrate],
    source: "tpwd-tx-reservoirs",
    natsur,
    natqua: null,
    encChart: spec.lakePageUrl,
  };
}

function buildLakeFeatures(
  spec: LakeSpec,
  esri: EsriPolygon,
  tpwdPts: TpwdPoint[],
): BundledFeature[] {
  const originLat = (spec.bbox[1] + spec.bbox[3]) / 2;
  const outerLocalRings: XY[][] = [];
  for (const ring of esri.rings) {
    const local = ring.map(([lo, la]) => toLocal(lo!, la!, originLat));
    if (local.length < 4) continue;
    const simplified = simplifyLocal(local, SIMPLIFY_TOLERANCE_M);
    if (simplified.length >= 4) outerLocalRings.push(simplified);
  }
  if (outerLocalRings.length === 0) return [];

  const mainBasinPolys: number[][][][] = [];
  const littoralPolys: number[][][][] = [];
  for (const outer of outerLocalRings) {
    const eroded = erodeRing(outer, spec.litoralBeltMeters);
    const outerLonLat = ringToLonLat(outer, originLat);
    if (eroded.length === 0) {
      littoralPolys.push([outerLonLat]);
      continue;
    }
    const erodedLonLat = ringToLonLat(eroded, originLat);
    mainBasinPolys.push([erodedLonLat]);
    littoralPolys.push([outerLonLat, erodedLonLat.slice().reverse()]);
  }

  const out: BundledFeature[] = [];

  // Mud basin
  if (mainBasinPolys.length === 1) {
    out.push({
      type: "Feature",
      properties: makeProps(spec, "mud", "Main basin / inundated channels (mud/clay)", "basin", spec.bottomNarrative),
      geometry: { type: "Polygon", coordinates: mainBasinPolys[0]! },
    });
  } else if (mainBasinPolys.length > 1) {
    out.push({
      type: "Feature",
      properties: makeProps(spec, "mud", "Main basin / inundated channels (mud/clay)", "basin", spec.bottomNarrative),
      geometry: { type: "MultiPolygon", coordinates: mainBasinPolys },
    });
  }
  // Sand littoral belt
  if (littoralPolys.length === 1) {
    out.push({
      type: "Feature",
      properties: makeProps(spec, "sand", "Littoral shoreline belt (sand/loam)", "littoral", spec.bottomNarrative),
      geometry: { type: "Polygon", coordinates: littoralPolys[0]! },
    });
  } else if (littoralPolys.length > 1) {
    out.push({
      type: "Feature",
      properties: makeProps(spec, "sand", "Littoral shoreline belt (sand/loam)", "littoral", spec.bottomNarrative),
      geometry: { type: "MultiPolygon", coordinates: littoralPolys },
    });
  }

  // Curated structure zones (small squares around documented features).
  for (const zone of spec.curatedZones) {
    const c = toLocal(zone.center[0], zone.center[1], originLat);
    const h = zone.halfWidthM;
    const local: XY[] = [
      { x: c.x - h, y: c.y - h },
      { x: c.x + h, y: c.y - h },
      { x: c.x + h, y: c.y + h },
      { x: c.x - h, y: c.y + h },
    ];
    out.push({
      type: "Feature",
      properties: makeProps(spec, zone.substrate, zone.label, `zone-${zone.id}`, zone.citation),
      geometry: { type: "Polygon", coordinates: [ringToLonLat(local, originLat)] },
    });
  }

  // TPWD habitat-structure clusters → gravel zones (one per cluster).
  if (tpwdPts.length > 0) {
    const localPts = tpwdPts.map((p) => toLocal(p.lon, p.lat, originLat));
    const groups = clusterByDistance(localPts, spec.habitatClusterMeters);
    let emitted = 0;
    for (const idxs of groups) {
      if (idxs.length < spec.habitatMinClusterPoints) continue;
      const groupXY = idxs.map((i) => localPts[i]!);
      const hull = convexHull(groupXY);
      const buffered = bufferConvexRing(hull, Math.max(60, spec.habitatClusterMeters * 0.4), 8);
      if (buffered.length < 4) continue;
      const detail = tpwdPts[idxs[0]!]!.typeDetail || tpwdPts[idxs[0]!]!.typeGeneral || "structure";
      emitted += 1;
      out.push({
        type: "Feature",
        properties: makeProps(
          spec,
          "gravel",
          `TPWD habitat-structure cluster (${detail}, n=${idxs.length})`,
          `tpwd-cluster-${emitted}`,
          `TPWD-deployed fish habitat structures (${detail}); ${idxs.length} sites grouped within ${spec.habitatClusterMeters} m.`,
        ),
        geometry: { type: "Polygon", coordinates: [ringToLonLat(buffered, originLat)] },
      });
    }
    console.log(`    TPWD clusters: ${groups.length} groups, emitted ${emitted}`);
  }

  return out;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("=== build-tx-lake-substrate ===");
  const allFeatures: BundledFeature[] = [];
  let bbox: [number, number, number, number] = [
    Infinity, Infinity, -Infinity, -Infinity,
  ];
  for (const spec of LAKES) {
    console.log(`  ${spec.datasetId}: fetching NHD waterbody + TPWD habitat…`);
    const lake = await fetchNhdWaterbody(spec);
    if (!lake) {
      console.warn(`    no NHD waterbody found for ${spec.datasetId} — skipping`);
      continue;
    }
    const tpwd = await fetchTpwdHabitatPoints(spec);
    console.log(`    TPWD habitat-structure points: ${tpwd.length}`);
    const feats = buildLakeFeatures(spec, lake, tpwd);
    console.log(`    built ${feats.length} substrate feature(s)`);
    allFeatures.push(...feats);
    bbox = [
      Math.min(bbox[0], spec.bbox[0]),
      Math.min(bbox[1], spec.bbox[1]),
      Math.max(bbox[2], spec.bbox[2]),
      Math.max(bbox[3], spec.bbox[3]),
    ];
  }
  const counts: Record<string, number> = {};
  for (const f of allFeatures) counts[f.properties.substrate] = (counts[f.properties.substrate] ?? 0) + 1;
  console.log(`  Bundled: ${allFeatures.length} features; distribution ${JSON.stringify(counts)}`);

  const bundle: BundledCollection = {
    type: "FeatureCollection",
    features: allFeatures,
    metadata: {
      region:
        "Texas freshwater reservoirs (Lake Fork, Sam Rayburn, Ray Roberts, Toledo Bend) — NHD outline + TPWD/TWDB substrate + TPWD habitat-structure clusters",
      bbox,
      source: "tpwd-tx-reservoirs",
      sourceName:
        "USGS NHD Waterbody outlines classified by TPWD Inland Fisheries lake-survey reports, TWDB volumetric/sedimentation surveys, and TPWD Texas Fish Habitat Structures FeatureServer",
      sourceLayer:
        "NHD MapServer/12 (Waterbody) + TPWD Texas_Fish_Habitat_Structures_20221206 + TPWD lake-bottom narratives",
      sourceService: NHD_WATERBODY,
      creditUrl:
        "https://tpwd.texas.gov/fishing/freshwater-fishing/where-to-fish/freshwater-lakes/",
      fetchedAt: new Date().toISOString(),
      featureCount: allFeatures.length,
    },
  };

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, JSON.stringify(bundle), "utf8");
  console.log(`  Wrote ${OUT_PATH}`);
  console.log("=== done ===");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
