/**
 * Real Alaska ShoreZone substrate polygons.
 *
 * Source: Alaska ShoreZone Coastal Habitat Mapping Program (NOAA AKR / ADF&G).
 *   Layer:   AK_SZ_ITZ_Polygons (intertidal-zone polygons)
 *   Service: https://services9.arcgis.com/ayzk2J4kDK5FpHqs/arcgis/rest/services/AK_SZ_ITZ_Polygons/FeatureServer/9
 *   Program: https://alaskafisheries.noaa.gov/shorezone/
 *
 * The actual GeoJSON FeatureCollection lives in `./shoreZoneData.alaska.gen.ts`
 * — that file is generated by
 *   `pnpm --filter @workspace/scripts run build-shorezone`
 * which pulls polygons directly from the public ArcGIS Feature Service and
 * classifies each polygon's Mat_Desc + Form_Desc into a CMECS broad substrate
 * class (bedrock / gravel / sand / mud).
 *
 * Coverage note: the public AK_SZ_ITZ_Polygons layer currently covers
 * ~58.4–59.1°N / 137.1–135.8°W (Glacier Bay / Icy Strait area). Other Alaska
 * ShoreZone surveys exist as separate program shapefiles but are not published
 * through this service. The `/api/substrate/:id` route therefore filters this
 * regional bundle to each dataset's AOI bbox at request time; datasets whose
 * AOI does not overlap published ShoreZone coverage (e.g. Thorne Bay /
 * Prince of Wales Island) receive an honest empty FeatureCollection together
 * with metadata describing where real ShoreZone coverage actually exists.
 */

export type ShoreZoneSubstrate = "bedrock" | "gravel" | "sand" | "mud";

export interface ShoreZoneFeature {
  type: "Feature";
  properties: {
    /** ShoreZone PHY_IDENT — stable unit identifier. */
    unitId: string;
    /** CMECS broad substrate class derived from szMaterial + szForm. */
    substrate: ShoreZoneSubstrate;
    /** Human-readable ShoreZone class, e.g. "Rock Platform", "Clastic Beach". */
    shoreZoneClass: string;
    /** CMECS classification code. */
    cmecsCode: string;
    /** Suggested hex colour for rendering. */
    color: string;
    /** Raw ShoreZone Mat_Desc (Rock / Clastic / Biogenic). */
    szMaterial: string | null;
    /** Raw ShoreZone Form_Desc (Cliff / Platform / Beach / Tidal Flat / Marsh). */
    szForm: string | null;
    /** Polygon area in square metres, from upstream Area attribute. */
    areaSqM: number | null;
  };
  geometry:
    | { type: "Polygon"; coordinates: number[][][] }
    | { type: "MultiPolygon"; coordinates: number[][][][] };
}

export interface ShoreZoneFeatureCollection {
  type: "FeatureCollection";
  features: ShoreZoneFeature[];
  metadata: {
    region: string;
    bbox: [number, number, number, number];
    source: "alaska-shorezone";
    sourceName: string;
    sourceLayer: string;
    sourceService: string;
    creditUrl: string;
    fetchedAt: string;
    featureCount: number;
  };
}

import { ALASKA_SHOREZONE_RAW } from "./shoreZoneData.alaska.gen.js";

/** The full bundled Alaska ShoreZone regional FeatureCollection. */
export const ALASKA_SHOREZONE: ShoreZoneFeatureCollection = ALASKA_SHOREZONE_RAW;

export interface Bbox {
  minLon: number;
  minLat: number;
  maxLon: number;
  maxLat: number;
}

function ringBbox(
  ring: number[][],
): { minLon: number; minLat: number; maxLon: number; maxLat: number } {
  let minLon = Infinity, minLat = Infinity, maxLon = -Infinity, maxLat = -Infinity;
  for (const c of ring) {
    const lon = c[0]!, lat = c[1]!;
    if (lon < minLon) minLon = lon;
    if (lon > maxLon) maxLon = lon;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  return { minLon, minLat, maxLon, maxLat };
}

function featureBbox(feature: ShoreZoneFeature): {
  minLon: number; minLat: number; maxLon: number; maxLat: number;
} {
  const polygons: number[][][][] =
    feature.geometry.type === "Polygon"
      ? [feature.geometry.coordinates]
      : feature.geometry.coordinates;
  let minLon = Infinity, minLat = Infinity, maxLon = -Infinity, maxLat = -Infinity;
  for (const poly of polygons) {
    for (const ring of poly) {
      const b = ringBbox(ring);
      if (b.minLon < minLon) minLon = b.minLon;
      if (b.minLat < minLat) minLat = b.minLat;
      if (b.maxLon > maxLon) maxLon = b.maxLon;
      if (b.maxLat > maxLat) maxLat = b.maxLat;
    }
  }
  return { minLon, minLat, maxLon, maxLat };
}

/** Return the subset of ALASKA_SHOREZONE whose bbox overlaps `bbox`. */
export function getShoreZoneIntersectingBbox(bbox: Bbox): ShoreZoneFeature[] {
  return ALASKA_SHOREZONE.features.filter((f) => {
    const b = featureBbox(f);
    return (
      b.maxLon >= bbox.minLon &&
      b.minLon <= bbox.maxLon &&
      b.maxLat >= bbox.minLat &&
      b.minLat <= bbox.maxLat
    );
  });
}

/**
 * Great-circle distance between two lat/lon points in kilometres
 * (Haversine, R = 6371 km).
 */
function haversineKm(
  aLat: number, aLon: number, bLat: number, bLon: number,
): number {
  const toRad = (d: number): number => (d * Math.PI) / 180;
  const R = 6371;
  const dLat = toRad(bLat - aLat);
  const dLon = toRad(bLon - aLon);
  const lat1 = toRad(aLat);
  const lat2 = toRad(bLat);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/**
 * Approximate distance in km from a query bbox to the nearest ShoreZone
 * feature, measured between bbox centres (good enough for an explanatory
 * "nearest coverage" hint in API responses).
 */
export function nearestCoverageKm(bbox: Bbox): number {
  const qLat = (bbox.minLat + bbox.maxLat) / 2;
  const qLon = (bbox.minLon + bbox.maxLon) / 2;
  let best = Infinity;
  for (const f of ALASKA_SHOREZONE.features) {
    const b = featureBbox(f);
    const fLat = (b.minLat + b.maxLat) / 2;
    const fLon = (b.minLon + b.maxLon) / 2;
    const d = haversineKm(qLat, qLon, fLat, fLon);
    if (d < best) best = d;
  }
  return best;
}
