import { Router, type IRouter } from "express";
import healthRouter from "./health";
import poeRouter from "./poe";
import datasetsRouter from "./datasets";
import markersRouter from "./markers";
import catchesRouter from "./catches";
import objectsRouter from "./objects";
import settingsRouter from "./settings";
import userDatasetsRouter from "./user-datasets";
import foldersRouter from "./folders";
import tidalRouter from "./tidal";
import tidesRouter from "./tides";
import queryRouter from "./query";
import trailsRouter from "./trails";
import meRouter from "./me";
import substrateRouter from "./substrate";
import efhRouter from "./efh";
import intertidalSpotsRouter from "./intertidal-spots";
import catalogSavesRouter from "./catalog-saves";
import surfaceConditionsRouter from "./surface-conditions";
import trollingPresetsRouter from "./trolling-presets";
import trollingPresetFoldersRouter from "./trolling-preset-folders";
import waterTemperatureRouter from "./water-temperature";
import temperatureProfileRouter from "./temperature-profile";
import routesRouter from "./routes";
import weatherStationsRouter from "./weather-stations";
import weatherStationObsRouter from "./weather-station-obs";
import rawsStationsRouter from "./raws-stations";
import rawsWeatherRouter from "./raws-weather";
import nceiRouter from "./ncei";
import adminRouter from "./admin";
import githubRouter from "./github";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/poe", poeRouter);
router.use(datasetsRouter);
router.use(markersRouter);
router.use(catchesRouter);
router.use(objectsRouter);
router.use(settingsRouter);
router.use(userDatasetsRouter);
router.use(foldersRouter);
router.use(tidalRouter);
router.use(tidesRouter);
router.use(queryRouter);
router.use(trailsRouter);
router.use(meRouter);
router.use(substrateRouter);
router.use(efhRouter);
router.use(intertidalSpotsRouter);
router.use(catalogSavesRouter);
router.use(surfaceConditionsRouter);
router.use(trollingPresetsRouter);
router.use(trollingPresetFoldersRouter);
router.use(waterTemperatureRouter);
router.use(temperatureProfileRouter);
router.use(routesRouter);
router.use(weatherStationsRouter);
router.use(weatherStationObsRouter);
router.use(rawsStationsRouter);
router.use(rawsWeatherRouter);
router.use(nceiRouter);
router.use(adminRouter);
router.use("/github", githubRouter);

export default router;
